#
# =========================================================================
# =========================================================================
# ------------------- BEGIN directory specific part -----------------------
# =========================================================================

# >>>>>>>>>>>>>> include relative path to make_env.h file <<<<<<<<<<<<<<<<<<
include ../make_env.h

# >>>>>>>>>>>>>> define name of Java package <<<<<<<<<<<<<<<<<<<<<<<<<<
PACKAGE= edu.caltech.ipac.client


# >>>>>>>>>>>>>> define all Java class names without extension <<<<<<<<<<<
CLASS_NAMES = InterfaceToMac

# >>>>>>>>>>>>> Files here are in the resources sub-directory.
# >>>>>>>>>>>>> They will be moved to the class directory tree.
RESOURCES = 
              
InterfaceToMac_JAR_ENTRIES= \
            edu/caltech/ipac/client/InterfaceToMac*.class

InterfaceToMac_JAR_DESCRIPTION = with Mac Specific functions



# =========================================================================
# ------------------- END directory specific part -----------------------
# =========================================================================
# =========================================================================
#


include $(INCLUDEDIR)/Makefile.h
include $(INCLUDEDIR)/Makefile.targets

#================ Do not edit below this line =============================
#================ Generated by gmake depend   =============================
