version: '3'
services:
  firefly:
    image: ipac/firefly:${BUILD_TAG:-latest}  # value taken from shell, or latest
    build:
      context: ../
      dockerfile: firefly/docker/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment: # any variable listed in catalina.sh and usually set in tomcat's setenv.sh, could be set here
      - ADMIN_PASSWORD      # value taken from env
