package edu.caltech.ipac.firefly.core.background;
/**
 * User: roby
 * Date: Dec 15, 2009
 * Time: 10:51:06 AM
 */


/**
 * @author Trey Roby
 */
public enum BackgroundState {
    /**
     * WAITING - Waiting to start request
     */
    WAITING,
    /**
     * STARTING - Starting to package - used only on client side, before getting first status
     */
    STARTING,
    /**
     * server is working on the packaging
     */
    WORKING,
    /**
     * USER_ABORTED - user aborted the package - should only be set on client side
     */
    USER_ABORTED,
    /**
     * FAIL - server failed to package request
     */
    FAIL,
    /**
     * SUCCESS - server successfully packaged request
     */
    SUCCESS,
    /**
     * CANCELED - packaging was canceled, set by server when checking the canceled flag
     */
    CANCELED,
    /**
     * UNKNOWN_PACKAGE_ID - a status used for a request with a unknown package id
     */
    UNKNOWN_PACKAGE_ID
}

/*
 * THIS SOFTWARE AND ANY RELATED MATERIALS WERE CREATED BY THE CALIFORNIA 
 * INSTITUTE OF TECHNOLOGY (CALTECH) UNDER A U.S. GOVERNMENT CONTRACT WITH 
 * THE NATIONAL AERONAUTICS AND SPACE ADMINISTRATION (NASA). THE SOFTWARE 
 * IS TECHNOLOGY AND SOFTWARE PUBLICLY AVAILABLE UNDER U.S. EXPORT LAWS 
 * AND IS PROVIDED AS-IS TO THE RECIPIENT WITHOUT WARRANTY OF ANY KIND, 
 * INCLUDING ANY WARRANTIES OF PERFORMANCE OR MERCHANTABILITY OR FITNESS FOR 
 * A PARTICULAR USE OR PURPOSE (AS SET FORTH IN UNITED STATES UCC 2312- 2313) 
 * OR FOR ANY PURPOSE WHATSOEVER, FOR THE SOFTWARE AND RELATED MATERIALS, 
 * HOWEVER USED.
 * 
 * IN NO EVENT SHALL CALTECH, ITS JET PROPULSION LABORATORY, OR NASA BE LIABLE 
 * FOR ANY DAMAGES AND/OR COSTS, INCLUDING, BUT NOT LIMITED TO, INCIDENTAL 
 * OR CONSEQUENTIAL DAMAGES OF ANY KIND, INCLUDING ECONOMIC DAMAGE OR INJURY TO 
 * PROPERTY AND LOST PROFITS, REGARDLESS OF WHETHER CALTECH, JPL, OR NASA BE 
 * ADVISED, HAVE REASON TO KNOW, OR, IN FACT, SHALL KNOW OF THE POSSIBILITY.
 * 
 * RECIPIENT BEARS ALL RISK RELATING TO QUALITY AND PERFORMANCE OF THE SOFTWARE 
 * AND ANY RELATED MATERIALS, AND AGREES TO INDEMNIFY CALTECH AND NASA FOR 
 * ALL THIRD-PARTY CLAIMS RESULTING FROM THE ACTIONS OF RECIPIENT IN THE USE 
 * OF THE SOFTWARE. 
 */
