


export const RawDataThreadActions= {
    FETCH_DATA: 'FETCH_DATA',
    STRETCH: 'STRETCH',
    FETCH_STRETCH_BYTE_DATA: 'FETCH_STRETCH_BYTE_DATA',
    ABORT_FETCH: 'ABORT_FETCH',
    COLOR: 'COLOR',
    GET_FLUX: 'GET_FLUX',
    REMOVE_RAW_DATA: 'REMOVE_RAW_DATA',
};