ingress:
  tlsSecretName: firefly-ssl-cert

replicaCount: 1

image:
  repository: ipac/firefly
  pullPolicy: Always

resources:
  requests:
    memory: 1Gi
  limits:
    memory: 4Gi

persistence:
  sharedWorkDir:
    existingClaim: firefly-workarea
