ingress:
  tlsSecretName: firefly-ssl-cert

replicaCount: 2

image:
  repository: ipac/firefly
  pullPolicy: Always

resources:
  requests:
    memory: 4Gi
  limits:
    memory: 8Gi

persistence:
  sharedWorkDir:
    existingClaim: firefly-workarea
