-- example: dbaccess v1_5_heritage@sodb_test load.sql
delete from requestinformations_dd;
load from requestinformations_dd.dat delimiter '|' insert into requestinformations_dd;
delete from bcdproducts_dd;
load from bcdproducts_dd.dat delimiter '|' insert into bcdproducts_dd;
delete from postbcdproducts_dd;
load from postbcdproducts_dd.dat delimiter '|' insert into postbcdproducts_dd;
delete from iracmap_dd;
load from iracmap_dd.dat delimiter '|' insert into iracmap_dd;
delete from iracmappc_dd;
load from iracmappc_dd.dat delimiter '|' insert into iracmappc_dd;
delete from irsmap_dd;
load from irsmap_dd.dat delimiter '|' insert into irsmap_dd;
delete from irspeakupimage_dd;
load from irspeakupimage_dd.dat delimiter '|' insert into irspeakupimage_dd;
delete from irsstare_dd;
load from irsstare_dd.dat delimiter '|' insert into irsstare_dd;
delete from mipsphot_dd;
load from mipsphot_dd.dat delimiter '|' insert into mipsphot_dd;
delete from mipsscan_dd;
load from mipsscan_dd.dat delimiter '|' insert into mipsscan_dd;
delete from mipssed_dd;
load from mipssed_dd.dat delimiter '|' insert into mipssed_dd;
delete from mipstp_dd;
load from mipstp_dd.dat delimiter '|' insert into mipstp_dd;
