package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * BcdAncilProducts generated by hbm2java
 */
public class BcdAncilProducts  implements java.io.Serializable {


     private int ancilid;
     private BcdProducts bcdproducts;
     private int campid;
     private String heritagefilename;
     private String fileextension;
     private String type;
     private Integer ptid;
     private String ptcomment;
     private Integer filesize;
     private String checksum;
     private String archivefilename;

    public BcdAncilProducts() {
    }

	
    public BcdAncilProducts(int ancilid, BcdProducts bcdproducts, int campid, String type) {
        this.ancilid = ancilid;
        this.bcdproducts = bcdproducts;
        this.campid = campid;
        this.type = type;
    }
    public BcdAncilProducts(int ancilid, BcdProducts bcdproducts, int campid, String heritagefilename, String fileextension, String type, Integer ptid, String ptcomment, Integer filesize, String checksum, String archivefilename) {
       this.ancilid = ancilid;
       this.bcdproducts = bcdproducts;
       this.campid = campid;
       this.heritagefilename = heritagefilename;
       this.fileextension = fileextension;
       this.type = type;
       this.ptid = ptid;
       this.ptcomment = ptcomment;
       this.filesize = filesize;
       this.checksum = checksum;
       this.archivefilename = archivefilename;
    }
   
    public int getAncilid() {
        return this.ancilid;
    }
    
    public void setAncilid(int ancilid) {
        this.ancilid = ancilid;
    }
    public BcdProducts getBcdproducts() {
        return this.bcdproducts;
    }
    
    public void setBcdproducts(BcdProducts bcdproducts) {
        this.bcdproducts = bcdproducts;
    }
    public int getCampid() {
        return this.campid;
    }
    
    public void setCampid(int campid) {
        this.campid = campid;
    }
    public String getHeritagefilename() {
        return this.heritagefilename;
    }
    
    public void setHeritagefilename(String heritagefilename) {
        this.heritagefilename = heritagefilename;
    }
    public String getFileextension() {
        return this.fileextension;
    }
    
    public void setFileextension(String fileextension) {
        this.fileextension = fileextension;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Integer getPtid() {
        return this.ptid;
    }
    
    public void setPtid(Integer ptid) {
        this.ptid = ptid;
    }
    public String getPtcomment() {
        return this.ptcomment;
    }
    
    public void setPtcomment(String ptcomment) {
        this.ptcomment = ptcomment;
    }
    public Integer getFilesize() {
        return this.filesize;
    }
    
    public void setFilesize(Integer filesize) {
        this.filesize = filesize;
    }
    public String getChecksum() {
        return this.checksum;
    }
    
    public void setChecksum(String checksum) {
        this.checksum = checksum;
    }
    public String getArchivefilename() {
        return this.archivefilename;
    }
    
    public void setArchivefilename(String archivefilename) {
        this.archivefilename = archivefilename;
    }




}


