package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * Cal2Postbcd generated by hbm2java
 */
public class Cal2Postbcd  implements java.io.Serializable {


     private Cal2PostbcdId id;
     private CalibrationProducts calibrationproducts;

    public Cal2Postbcd() {
    }

    public Cal2Postbcd(Cal2PostbcdId id, CalibrationProducts calibrationproducts) {
       this.id = id;
       this.calibrationproducts = calibrationproducts;
    }
   
    public Cal2PostbcdId getId() {
        return this.id;
    }
    
    public void setId(Cal2PostbcdId id) {
        this.id = id;
    }
    public CalibrationProducts getCalibrationproducts() {
        return this.calibrationproducts;
    }
    
    public void setCalibrationproducts(CalibrationProducts calibrationproducts) {
        this.calibrationproducts = calibrationproducts;
    }




}


