package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * Cal2PostbcdId generated by hbm2java
 */
public class Cal2PostbcdId  implements java.io.Serializable {


     private int epid;
     private int cpid;

    public Cal2PostbcdId() {
    }

    public Cal2PostbcdId(int epid, int cpid) {
       this.epid = epid;
       this.cpid = cpid;
    }
   
    public int getEpid() {
        return this.epid;
    }
    
    public void setEpid(int epid) {
        this.epid = epid;
    }
    public int getCpid() {
        return this.cpid;
    }
    
    public void setCpid(int cpid) {
        this.cpid = cpid;
    }




}


