package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * CalibrationProducts generated by hbm2java
 */
public class CalibrationProducts  implements java.io.Serializable {


     private int cpid;
     private RequestInformation requestinformation;
     private int ensid;
     private int campid;
     private short chan0;
     private short chan1;
     private short chan2;
     private short chan3;
     private short chan4;
     private short plscriptid;
     private int dcesetid;
     private short ruleid;
     private String caltype;
     private Short actualinputs;
     private String heritagefilename;
     private Integer ptid;
     private String ptcomment;
     private int filesize;
     private String checksum;
     private double ra;
     private double dec;
     private String cra;
     private String cdec;
     private double crval1;
     private double crval2;
     private String ctype1;
     private String ctype2;
     private double crpix1;
     private double crpix2;
     private short naxis1;
     private short naxis2;
     private double cdelt1;
     private double cdelt2;
     private double crota2;
     private double epoch;
     private float equinox;
     private double ra1;
     private double dec1;
     private double ra2;
     private double dec2;
     private double ra3;
     private double dec3;
     private double ra4;
     private double dec4;
     private short hdu;
     private double x;
     private double y;
     private double z;
     private String archivefilename;
     private int ssccpid;

    public CalibrationProducts() {
    }

	
    public CalibrationProducts(int cpid, RequestInformation requestinformation, int ensid, int campid, short chan0, short chan1, short chan2, short chan3, short chan4, short plscriptid, int dcesetid, short ruleid, int filesize, String checksum, double ra, double dec, String cra, String cdec, double crval1, double crval2, String ctype1, String ctype2, double crpix1, double crpix2, short naxis1, short naxis2, double cdelt1, double cdelt2, double crota2, double epoch, float equinox, double ra1, double dec1, double ra2, double dec2, double ra3, double dec3, double ra4, double dec4, short hdu, double x, double y, double z, int ssccpid) {
        this.cpid = cpid;
        this.requestinformation = requestinformation;
        this.ensid = ensid;
        this.campid = campid;
        this.chan0 = chan0;
        this.chan1 = chan1;
        this.chan2 = chan2;
        this.chan3 = chan3;
        this.chan4 = chan4;
        this.plscriptid = plscriptid;
        this.dcesetid = dcesetid;
        this.ruleid = ruleid;
        this.filesize = filesize;
        this.checksum = checksum;
        this.ra = ra;
        this.dec = dec;
        this.cra = cra;
        this.cdec = cdec;
        this.crval1 = crval1;
        this.crval2 = crval2;
        this.ctype1 = ctype1;
        this.ctype2 = ctype2;
        this.crpix1 = crpix1;
        this.crpix2 = crpix2;
        this.naxis1 = naxis1;
        this.naxis2 = naxis2;
        this.cdelt1 = cdelt1;
        this.cdelt2 = cdelt2;
        this.crota2 = crota2;
        this.epoch = epoch;
        this.equinox = equinox;
        this.ra1 = ra1;
        this.dec1 = dec1;
        this.ra2 = ra2;
        this.dec2 = dec2;
        this.ra3 = ra3;
        this.dec3 = dec3;
        this.ra4 = ra4;
        this.dec4 = dec4;
        this.hdu = hdu;
        this.x = x;
        this.y = y;
        this.z = z;
        this.ssccpid = ssccpid;
    }
    public CalibrationProducts(int cpid, RequestInformation requestinformation, int ensid, int campid, short chan0, short chan1, short chan2, short chan3, short chan4, short plscriptid, int dcesetid, short ruleid, String caltype, Short actualinputs, String heritagefilename, Integer ptid, String ptcomment, int filesize, String checksum, double ra, double dec, String cra, String cdec, double crval1, double crval2, String ctype1, String ctype2, double crpix1, double crpix2, short naxis1, short naxis2, double cdelt1, double cdelt2, double crota2, double epoch, float equinox, double ra1, double dec1, double ra2, double dec2, double ra3, double dec3, double ra4, double dec4, short hdu, double x, double y, double z, String archivefilename, int ssccpid) {
       this.cpid = cpid;
       this.requestinformation = requestinformation;
       this.ensid = ensid;
       this.campid = campid;
       this.chan0 = chan0;
       this.chan1 = chan1;
       this.chan2 = chan2;
       this.chan3 = chan3;
       this.chan4 = chan4;
       this.plscriptid = plscriptid;
       this.dcesetid = dcesetid;
       this.ruleid = ruleid;
       this.caltype = caltype;
       this.actualinputs = actualinputs;
       this.heritagefilename = heritagefilename;
       this.ptid = ptid;
       this.ptcomment = ptcomment;
       this.filesize = filesize;
       this.checksum = checksum;
       this.ra = ra;
       this.dec = dec;
       this.cra = cra;
       this.cdec = cdec;
       this.crval1 = crval1;
       this.crval2 = crval2;
       this.ctype1 = ctype1;
       this.ctype2 = ctype2;
       this.crpix1 = crpix1;
       this.crpix2 = crpix2;
       this.naxis1 = naxis1;
       this.naxis2 = naxis2;
       this.cdelt1 = cdelt1;
       this.cdelt2 = cdelt2;
       this.crota2 = crota2;
       this.epoch = epoch;
       this.equinox = equinox;
       this.ra1 = ra1;
       this.dec1 = dec1;
       this.ra2 = ra2;
       this.dec2 = dec2;
       this.ra3 = ra3;
       this.dec3 = dec3;
       this.ra4 = ra4;
       this.dec4 = dec4;
       this.hdu = hdu;
       this.x = x;
       this.y = y;
       this.z = z;
       this.archivefilename = archivefilename;
       this.ssccpid = ssccpid;
    }
   
    public int getCpid() {
        return this.cpid;
    }
    
    public void setCpid(int cpid) {
        this.cpid = cpid;
    }
    public RequestInformation getRequestinformation() {
        return this.requestinformation;
    }
    
    public void setRequestinformation(RequestInformation requestinformation) {
        this.requestinformation = requestinformation;
    }
    public int getEnsid() {
        return this.ensid;
    }
    
    public void setEnsid(int ensid) {
        this.ensid = ensid;
    }
    public int getCampid() {
        return this.campid;
    }
    
    public void setCampid(int campid) {
        this.campid = campid;
    }
    public short getChan0() {
        return this.chan0;
    }
    
    public void setChan0(short chan0) {
        this.chan0 = chan0;
    }
    public short getChan1() {
        return this.chan1;
    }
    
    public void setChan1(short chan1) {
        this.chan1 = chan1;
    }
    public short getChan2() {
        return this.chan2;
    }
    
    public void setChan2(short chan2) {
        this.chan2 = chan2;
    }
    public short getChan3() {
        return this.chan3;
    }
    
    public void setChan3(short chan3) {
        this.chan3 = chan3;
    }
    public short getChan4() {
        return this.chan4;
    }
    
    public void setChan4(short chan4) {
        this.chan4 = chan4;
    }
    public short getPlscriptid() {
        return this.plscriptid;
    }
    
    public void setPlscriptid(short plscriptid) {
        this.plscriptid = plscriptid;
    }
    public int getDcesetid() {
        return this.dcesetid;
    }
    
    public void setDcesetid(int dcesetid) {
        this.dcesetid = dcesetid;
    }
    public short getRuleid() {
        return this.ruleid;
    }
    
    public void setRuleid(short ruleid) {
        this.ruleid = ruleid;
    }
    public String getCaltype() {
        return this.caltype;
    }
    
    public void setCaltype(String caltype) {
        this.caltype = caltype;
    }
    public Short getActualinputs() {
        return this.actualinputs;
    }
    
    public void setActualinputs(Short actualinputs) {
        this.actualinputs = actualinputs;
    }
    public String getHeritagefilename() {
        return this.heritagefilename;
    }
    
    public void setHeritagefilename(String heritagefilename) {
        this.heritagefilename = heritagefilename;
    }
    public Integer getPtid() {
        return this.ptid;
    }
    
    public void setPtid(Integer ptid) {
        this.ptid = ptid;
    }
    public String getPtcomment() {
        return this.ptcomment;
    }
    
    public void setPtcomment(String ptcomment) {
        this.ptcomment = ptcomment;
    }
    public int getFilesize() {
        return this.filesize;
    }
    
    public void setFilesize(int filesize) {
        this.filesize = filesize;
    }
    public String getChecksum() {
        return this.checksum;
    }
    
    public void setChecksum(String checksum) {
        this.checksum = checksum;
    }
    public double getRa() {
        return this.ra;
    }
    
    public void setRa(double ra) {
        this.ra = ra;
    }
    public double getDec() {
        return this.dec;
    }
    
    public void setDec(double dec) {
        this.dec = dec;
    }
    public String getCra() {
        return this.cra;
    }
    
    public void setCra(String cra) {
        this.cra = cra;
    }
    public String getCdec() {
        return this.cdec;
    }
    
    public void setCdec(String cdec) {
        this.cdec = cdec;
    }
    public double getCrval1() {
        return this.crval1;
    }
    
    public void setCrval1(double crval1) {
        this.crval1 = crval1;
    }
    public double getCrval2() {
        return this.crval2;
    }
    
    public void setCrval2(double crval2) {
        this.crval2 = crval2;
    }
    public String getCtype1() {
        return this.ctype1;
    }
    
    public void setCtype1(String ctype1) {
        this.ctype1 = ctype1;
    }
    public String getCtype2() {
        return this.ctype2;
    }
    
    public void setCtype2(String ctype2) {
        this.ctype2 = ctype2;
    }
    public double getCrpix1() {
        return this.crpix1;
    }
    
    public void setCrpix1(double crpix1) {
        this.crpix1 = crpix1;
    }
    public double getCrpix2() {
        return this.crpix2;
    }
    
    public void setCrpix2(double crpix2) {
        this.crpix2 = crpix2;
    }
    public short getNaxis1() {
        return this.naxis1;
    }
    
    public void setNaxis1(short naxis1) {
        this.naxis1 = naxis1;
    }
    public short getNaxis2() {
        return this.naxis2;
    }
    
    public void setNaxis2(short naxis2) {
        this.naxis2 = naxis2;
    }
    public double getCdelt1() {
        return this.cdelt1;
    }
    
    public void setCdelt1(double cdelt1) {
        this.cdelt1 = cdelt1;
    }
    public double getCdelt2() {
        return this.cdelt2;
    }
    
    public void setCdelt2(double cdelt2) {
        this.cdelt2 = cdelt2;
    }
    public double getCrota2() {
        return this.crota2;
    }
    
    public void setCrota2(double crota2) {
        this.crota2 = crota2;
    }
    public double getEpoch() {
        return this.epoch;
    }
    
    public void setEpoch(double epoch) {
        this.epoch = epoch;
    }
    public float getEquinox() {
        return this.equinox;
    }
    
    public void setEquinox(float equinox) {
        this.equinox = equinox;
    }
    public double getRa1() {
        return this.ra1;
    }
    
    public void setRa1(double ra1) {
        this.ra1 = ra1;
    }
    public double getDec1() {
        return this.dec1;
    }
    
    public void setDec1(double dec1) {
        this.dec1 = dec1;
    }
    public double getRa2() {
        return this.ra2;
    }
    
    public void setRa2(double ra2) {
        this.ra2 = ra2;
    }
    public double getDec2() {
        return this.dec2;
    }
    
    public void setDec2(double dec2) {
        this.dec2 = dec2;
    }
    public double getRa3() {
        return this.ra3;
    }
    
    public void setRa3(double ra3) {
        this.ra3 = ra3;
    }
    public double getDec3() {
        return this.dec3;
    }
    
    public void setDec3(double dec3) {
        this.dec3 = dec3;
    }
    public double getRa4() {
        return this.ra4;
    }
    
    public void setRa4(double ra4) {
        this.ra4 = ra4;
    }
    public double getDec4() {
        return this.dec4;
    }
    
    public void setDec4(double dec4) {
        this.dec4 = dec4;
    }
    public short getHdu() {
        return this.hdu;
    }
    
    public void setHdu(short hdu) {
        this.hdu = hdu;
    }
    public double getX() {
        return this.x;
    }
    
    public void setX(double x) {
        this.x = x;
    }
    public double getY() {
        return this.y;
    }
    
    public void setY(double y) {
        this.y = y;
    }
    public double getZ() {
        return this.z;
    }
    
    public void setZ(double z) {
        this.z = z;
    }
    public String getArchivefilename() {
        return this.archivefilename;
    }
    
    public void setArchivefilename(String archivefilename) {
        this.archivefilename = archivefilename;
    }
    public int getSsccpid() {
        return this.ssccpid;
    }
    
    public void setSsccpid(int ssccpid) {
        this.ssccpid = ssccpid;
    }




}


