package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * CalibrationAncilProducts generated by hbm2java
 */
public class CalibrationAncilProducts  implements java.io.Serializable {


     private int ancilid;
     private CalibrationProducts calibrationproducts;
     private int campid;
     private String heritagefilename;
     private String fileextension;
     private String type;
     private Integer ptid;
     private String ptcomment;
     private int filesize;
     private String checksum;
     private int sscancilid;
     private String archivefilename;

    public CalibrationAncilProducts() {
    }

	
    public CalibrationAncilProducts(int ancilid, CalibrationProducts calibrationproducts, int campid, String type, int filesize, String checksum, int sscancilid) {
        this.ancilid = ancilid;
        this.calibrationproducts = calibrationproducts;
        this.campid = campid;
        this.type = type;
        this.filesize = filesize;
        this.checksum = checksum;
        this.sscancilid = sscancilid;
    }
    public CalibrationAncilProducts(int ancilid, CalibrationProducts calibrationproducts, int campid, String heritagefilename, String fileextension, String type, Integer ptid, String ptcomment, int filesize, String checksum, int sscancilid, String archivefilename) {
       this.ancilid = ancilid;
       this.calibrationproducts = calibrationproducts;
       this.campid = campid;
       this.heritagefilename = heritagefilename;
       this.fileextension = fileextension;
       this.type = type;
       this.ptid = ptid;
       this.ptcomment = ptcomment;
       this.filesize = filesize;
       this.checksum = checksum;
       this.sscancilid = sscancilid;
       this.archivefilename = archivefilename;
    }
   
    public int getAncilid() {
        return this.ancilid;
    }
    
    public void setAncilid(int ancilid) {
        this.ancilid = ancilid;
    }
    public CalibrationProducts getCalibrationproducts() {
        return this.calibrationproducts;
    }
    
    public void setCalibrationproducts(CalibrationProducts calibrationproducts) {
        this.calibrationproducts = calibrationproducts;
    }
    public int getCampid() {
        return this.campid;
    }
    
    public void setCampid(int campid) {
        this.campid = campid;
    }
    public String getHeritagefilename() {
        return this.heritagefilename;
    }
    
    public void setHeritagefilename(String heritagefilename) {
        this.heritagefilename = heritagefilename;
    }
    public String getFileextension() {
        return this.fileextension;
    }
    
    public void setFileextension(String fileextension) {
        this.fileextension = fileextension;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Integer getPtid() {
        return this.ptid;
    }
    
    public void setPtid(Integer ptid) {
        this.ptid = ptid;
    }
    public String getPtcomment() {
        return this.ptcomment;
    }
    
    public void setPtcomment(String ptcomment) {
        this.ptcomment = ptcomment;
    }
    public int getFilesize() {
        return this.filesize;
    }
    
    public void setFilesize(int filesize) {
        this.filesize = filesize;
    }
    public String getChecksum() {
        return this.checksum;
    }
    
    public void setChecksum(String checksum) {
        this.checksum = checksum;
    }
    public int getSscancilid() {
        return this.sscancilid;
    }
    
    public void setSscancilid(int sscancilid) {
        this.sscancilid = sscancilid;
    }
    public String getArchivefilename() {
        return this.archivefilename;
    }
    
    public void setArchivefilename(String archivefilename) {
        this.archivefilename = archivefilename;
    }




}


