package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CampaignInformation generated by hbm2java
 */
public class CampaignInformation  implements java.io.Serializable {


     private int campid;
     private String campname;
     private Date campstarttime;
     private Date campendtime;
     private short warm;
     private int pvid;
     private Date certifieddate;
     private short chan0;
     private short chan1;
     private short chan2;
     private short chan3;
     private short chan4;
     private String heritagedir;

    public CampaignInformation() {
    }

	
    public CampaignInformation(int campid, String campname, Date campstarttime, Date campendtime, short warm, int pvid, Date certifieddate, short chan0, short chan1, short chan2, short chan3, short chan4) {
        this.campid = campid;
        this.campname = campname;
        this.campstarttime = campstarttime;
        this.campendtime = campendtime;
        this.warm = warm;
        this.pvid = pvid;
        this.certifieddate = certifieddate;
        this.chan0 = chan0;
        this.chan1 = chan1;
        this.chan2 = chan2;
        this.chan3 = chan3;
        this.chan4 = chan4;
    }
    public CampaignInformation(int campid, String campname, Date campstarttime, Date campendtime, short warm, int pvid, Date certifieddate, short chan0, short chan1, short chan2, short chan3, short chan4, String heritagedir) {
       this.campid = campid;
       this.campname = campname;
       this.campstarttime = campstarttime;
       this.campendtime = campendtime;
       this.warm = warm;
       this.pvid = pvid;
       this.certifieddate = certifieddate;
       this.chan0 = chan0;
       this.chan1 = chan1;
       this.chan2 = chan2;
       this.chan3 = chan3;
       this.chan4 = chan4;
       this.heritagedir = heritagedir;
    }
   
    public int getCampid() {
        return this.campid;
    }
    
    public void setCampid(int campid) {
        this.campid = campid;
    }
    public String getCampname() {
        return this.campname;
    }
    
    public void setCampname(String campname) {
        this.campname = campname;
    }
    public Date getCampstarttime() {
        return this.campstarttime;
    }
    
    public void setCampstarttime(Date campstarttime) {
        this.campstarttime = campstarttime;
    }
    public Date getCampendtime() {
        return this.campendtime;
    }
    
    public void setCampendtime(Date campendtime) {
        this.campendtime = campendtime;
    }
    public short getWarm() {
        return this.warm;
    }
    
    public void setWarm(short warm) {
        this.warm = warm;
    }
    public int getPvid() {
        return this.pvid;
    }
    
    public void setPvid(int pvid) {
        this.pvid = pvid;
    }
    public Date getCertifieddate() {
        return this.certifieddate;
    }
    
    public void setCertifieddate(Date certifieddate) {
        this.certifieddate = certifieddate;
    }
    public short getChan0() {
        return this.chan0;
    }
    
    public void setChan0(short chan0) {
        this.chan0 = chan0;
    }
    public short getChan1() {
        return this.chan1;
    }
    
    public void setChan1(short chan1) {
        this.chan1 = chan1;
    }
    public short getChan2() {
        return this.chan2;
    }
    
    public void setChan2(short chan2) {
        this.chan2 = chan2;
    }
    public short getChan3() {
        return this.chan3;
    }
    
    public void setChan3(short chan3) {
        this.chan3 = chan3;
    }
    public short getChan4() {
        return this.chan4;
    }
    
    public void setChan4(short chan4) {
        this.chan4 = chan4;
    }
    public String getHeritagedir() {
        return this.heritagedir;
    }
    
    public void setHeritagedir(String heritagedir) {
        this.heritagedir = heritagedir;
    }




}


