package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * ConstraintInformation generated by hbm2java
 */
public class ConstraintInformation  implements java.io.Serializable {


     private ConstraintInformationId id;
     private RequestInformation requestinformation;
     private String constrtype;
     private int progid;
     private String constrname;
     private String comment;
     private String slot;
     private String start;
     private String stop;
     private short shadowfirst;
     private short seqnum;

    public ConstraintInformation() {
    }

	
    public ConstraintInformation(ConstraintInformationId id, RequestInformation requestinformation, int progid, short shadowfirst, short seqnum) {
        this.id = id;
        this.requestinformation = requestinformation;
        this.progid = progid;
        this.shadowfirst = shadowfirst;
        this.seqnum = seqnum;
    }
    public ConstraintInformation(ConstraintInformationId id, RequestInformation requestinformation, String constrtype, int progid, String constrname, String comment, String slot, String start, String stop, short shadowfirst, short seqnum) {
       this.id = id;
       this.requestinformation = requestinformation;
       this.constrtype = constrtype;
       this.progid = progid;
       this.constrname = constrname;
       this.comment = comment;
       this.slot = slot;
       this.start = start;
       this.stop = stop;
       this.shadowfirst = shadowfirst;
       this.seqnum = seqnum;
    }
   
    public ConstraintInformationId getId() {
        return this.id;
    }
    
    public void setId(ConstraintInformationId id) {
        this.id = id;
    }
    public RequestInformation getRequestinformation() {
        return this.requestinformation;
    }
    
    public void setRequestinformation(RequestInformation requestinformation) {
        this.requestinformation = requestinformation;
    }
    public String getConstrtype() {
        return this.constrtype;
    }
    
    public void setConstrtype(String constrtype) {
        this.constrtype = constrtype;
    }
    public int getProgid() {
        return this.progid;
    }
    
    public void setProgid(int progid) {
        this.progid = progid;
    }
    public String getConstrname() {
        return this.constrname;
    }
    
    public void setConstrname(String constrname) {
        this.constrname = constrname;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getSlot() {
        return this.slot;
    }
    
    public void setSlot(String slot) {
        this.slot = slot;
    }
    public String getStart() {
        return this.start;
    }
    
    public void setStart(String start) {
        this.start = start;
    }
    public String getStop() {
        return this.stop;
    }
    
    public void setStop(String stop) {
        this.stop = stop;
    }
    public short getShadowfirst() {
        return this.shadowfirst;
    }
    
    public void setShadowfirst(short shadowfirst) {
        this.shadowfirst = shadowfirst;
    }
    public short getSeqnum() {
        return this.seqnum;
    }
    
    public void setSeqnum(short seqnum) {
        this.seqnum = seqnum;
    }




}


