package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * ConstraintInformationId generated by hbm2java
 */
public class ConstraintInformationId  implements java.io.Serializable {


     private int constrid;
     private int reqkey;

    public ConstraintInformationId() {
    }

    public ConstraintInformationId(int constrid, int reqkey) {
       this.constrid = constrid;
       this.reqkey = reqkey;
    }
   
    public int getConstrid() {
        return this.constrid;
    }
    
    public void setConstrid(int constrid) {
        this.constrid = constrid;
    }
    public int getReqkey() {
        return this.reqkey;
    }
    
    public void setReqkey(int reqkey) {
        this.reqkey = reqkey;
    }




}


