package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * DceInformation generated by hbm2java
 */
public class DceInformation  implements java.io.Serializable {


     private int dceid;
     private RequestInformation requestinformation;
     private PointingFiles pointingfiles;
     private int exposureid;
     private int campid;
     private short exposurenum;
     private Short cyclenum;
     private short aperture;
     private String exposuretype;
     private String readoutmode;
     private Short maprownum;
     private Short mapcolnum;
     private Short mapcyclenum;
     private Short ditherposnum;
     private Short clusterposnum;
     private Short scanlegnum;
     private String scandir;
     private Short posindex;
     private Short rampslope;
     private Double omega;
     private Short scanpos1;
     private Short scanpos2;
     private Short relpos1;
     private Short relpos2;
     private Short stepoffset;
     private Short rampdir;
     private Short stimcycle;
     private Short framenum;
     private short channum;
     private short dcenum;
     private Short fowlernum;
     private Integer waitperiod;
     private Double raj2000predict;
     private Double decj2000predict;
     private Double raj2000reference;
     private Double decj2000reference;
     private Double posanglereference;
     private Double raicrsactual;
     private Double decicrsactual;
     private Double posangleactual;
     private Integer ptgftid;
     private Short numptgfiles;
     private Double sclk;
     private Date scet;
     private String instrument;
     private Short initplscriptid;
     private Double frametime;
     private Double exposuretime;
     private Float compressratio;
     private short primaryfield;
     private Short defaultplscriptid;
     private Double scanmirrordac;
     private Double scanmirroraxisangledegrees;
     private Integer dceinsid;
     private String filename;
     private Date receivedat;
     private Short datamissing;
     private Short linesmissing;
     private Short percentmissing;
     private Short ancilmissing;
     private String externalname;
     private Integer filesize;

    public DceInformation() {
    }

	
    public DceInformation(int dceid, RequestInformation requestinformation, int exposureid, int campid, short exposurenum, short aperture, short channum, short dcenum, short primaryfield) {
        this.dceid = dceid;
        this.requestinformation = requestinformation;
        this.exposureid = exposureid;
        this.campid = campid;
        this.exposurenum = exposurenum;
        this.aperture = aperture;
        this.channum = channum;
        this.dcenum = dcenum;
        this.primaryfield = primaryfield;
    }
    public DceInformation(int dceid, RequestInformation requestinformation, PointingFiles pointingfiles, int exposureid, int campid, short exposurenum, Short cyclenum, short aperture, String exposuretype, String readoutmode, Short maprownum, Short mapcolnum, Short mapcyclenum, Short ditherposnum, Short clusterposnum, Short scanlegnum, String scandir, Short posindex, Short rampslope, Double omega, Short scanpos1, Short scanpos2, Short relpos1, Short relpos2, Short stepoffset, Short rampdir, Short stimcycle, Short framenum, short channum, short dcenum, Short fowlernum, Integer waitperiod, Double raj2000predict, Double decj2000predict, Double raj2000reference, Double decj2000reference, Double posanglereference, Double raicrsactual, Double decicrsactual, Double posangleactual, Integer ptgftid, Short numptgfiles, Double sclk, Date scet, String instrument, Short initplscriptid, Double frametime, Double exposuretime, Float compressratio, short primaryfield, Short defaultplscriptid, Double scanmirrordac, Double scanmirroraxisangledegrees, Integer dceinsid, String filename, Date receivedat, Short datamissing, Short linesmissing, Short percentmissing, Short ancilmissing, String externalname, Integer filesize) {
       this.dceid = dceid;
       this.requestinformation = requestinformation;
       this.pointingfiles = pointingfiles;
       this.exposureid = exposureid;
       this.campid = campid;
       this.exposurenum = exposurenum;
       this.cyclenum = cyclenum;
       this.aperture = aperture;
       this.exposuretype = exposuretype;
       this.readoutmode = readoutmode;
       this.maprownum = maprownum;
       this.mapcolnum = mapcolnum;
       this.mapcyclenum = mapcyclenum;
       this.ditherposnum = ditherposnum;
       this.clusterposnum = clusterposnum;
       this.scanlegnum = scanlegnum;
       this.scandir = scandir;
       this.posindex = posindex;
       this.rampslope = rampslope;
       this.omega = omega;
       this.scanpos1 = scanpos1;
       this.scanpos2 = scanpos2;
       this.relpos1 = relpos1;
       this.relpos2 = relpos2;
       this.stepoffset = stepoffset;
       this.rampdir = rampdir;
       this.stimcycle = stimcycle;
       this.framenum = framenum;
       this.channum = channum;
       this.dcenum = dcenum;
       this.fowlernum = fowlernum;
       this.waitperiod = waitperiod;
       this.raj2000predict = raj2000predict;
       this.decj2000predict = decj2000predict;
       this.raj2000reference = raj2000reference;
       this.decj2000reference = decj2000reference;
       this.posanglereference = posanglereference;
       this.raicrsactual = raicrsactual;
       this.decicrsactual = decicrsactual;
       this.posangleactual = posangleactual;
       this.ptgftid = ptgftid;
       this.numptgfiles = numptgfiles;
       this.sclk = sclk;
       this.scet = scet;
       this.instrument = instrument;
       this.initplscriptid = initplscriptid;
       this.frametime = frametime;
       this.exposuretime = exposuretime;
       this.compressratio = compressratio;
       this.primaryfield = primaryfield;
       this.defaultplscriptid = defaultplscriptid;
       this.scanmirrordac = scanmirrordac;
       this.scanmirroraxisangledegrees = scanmirroraxisangledegrees;
       this.dceinsid = dceinsid;
       this.filename = filename;
       this.receivedat = receivedat;
       this.datamissing = datamissing;
       this.linesmissing = linesmissing;
       this.percentmissing = percentmissing;
       this.ancilmissing = ancilmissing;
       this.externalname = externalname;
       this.filesize = filesize;
    }
   
    public int getDceid() {
        return this.dceid;
    }
    
    public void setDceid(int dceid) {
        this.dceid = dceid;
    }
    public RequestInformation getRequestinformation() {
        return this.requestinformation;
    }
    
    public void setRequestinformation(RequestInformation requestinformation) {
        this.requestinformation = requestinformation;
    }
    public PointingFiles getPointingfiles() {
        return this.pointingfiles;
    }
    
    public void setPointingfiles(PointingFiles pointingfiles) {
        this.pointingfiles = pointingfiles;
    }
    public int getExposureid() {
        return this.exposureid;
    }
    
    public void setExposureid(int exposureid) {
        this.exposureid = exposureid;
    }
    public int getCampid() {
        return this.campid;
    }
    
    public void setCampid(int campid) {
        this.campid = campid;
    }
    public short getExposurenum() {
        return this.exposurenum;
    }
    
    public void setExposurenum(short exposurenum) {
        this.exposurenum = exposurenum;
    }
    public Short getCyclenum() {
        return this.cyclenum;
    }
    
    public void setCyclenum(Short cyclenum) {
        this.cyclenum = cyclenum;
    }
    public short getAperture() {
        return this.aperture;
    }
    
    public void setAperture(short aperture) {
        this.aperture = aperture;
    }
    public String getExposuretype() {
        return this.exposuretype;
    }
    
    public void setExposuretype(String exposuretype) {
        this.exposuretype = exposuretype;
    }
    public String getReadoutmode() {
        return this.readoutmode;
    }
    
    public void setReadoutmode(String readoutmode) {
        this.readoutmode = readoutmode;
    }
    public Short getMaprownum() {
        return this.maprownum;
    }
    
    public void setMaprownum(Short maprownum) {
        this.maprownum = maprownum;
    }
    public Short getMapcolnum() {
        return this.mapcolnum;
    }
    
    public void setMapcolnum(Short mapcolnum) {
        this.mapcolnum = mapcolnum;
    }
    public Short getMapcyclenum() {
        return this.mapcyclenum;
    }
    
    public void setMapcyclenum(Short mapcyclenum) {
        this.mapcyclenum = mapcyclenum;
    }
    public Short getDitherposnum() {
        return this.ditherposnum;
    }
    
    public void setDitherposnum(Short ditherposnum) {
        this.ditherposnum = ditherposnum;
    }
    public Short getClusterposnum() {
        return this.clusterposnum;
    }
    
    public void setClusterposnum(Short clusterposnum) {
        this.clusterposnum = clusterposnum;
    }
    public Short getScanlegnum() {
        return this.scanlegnum;
    }
    
    public void setScanlegnum(Short scanlegnum) {
        this.scanlegnum = scanlegnum;
    }
    public String getScandir() {
        return this.scandir;
    }
    
    public void setScandir(String scandir) {
        this.scandir = scandir;
    }
    public Short getPosindex() {
        return this.posindex;
    }
    
    public void setPosindex(Short posindex) {
        this.posindex = posindex;
    }
    public Short getRampslope() {
        return this.rampslope;
    }
    
    public void setRampslope(Short rampslope) {
        this.rampslope = rampslope;
    }
    public Double getOmega() {
        return this.omega;
    }
    
    public void setOmega(Double omega) {
        this.omega = omega;
    }
    public Short getScanpos1() {
        return this.scanpos1;
    }
    
    public void setScanpos1(Short scanpos1) {
        this.scanpos1 = scanpos1;
    }
    public Short getScanpos2() {
        return this.scanpos2;
    }
    
    public void setScanpos2(Short scanpos2) {
        this.scanpos2 = scanpos2;
    }
    public Short getRelpos1() {
        return this.relpos1;
    }
    
    public void setRelpos1(Short relpos1) {
        this.relpos1 = relpos1;
    }
    public Short getRelpos2() {
        return this.relpos2;
    }
    
    public void setRelpos2(Short relpos2) {
        this.relpos2 = relpos2;
    }
    public Short getStepoffset() {
        return this.stepoffset;
    }
    
    public void setStepoffset(Short stepoffset) {
        this.stepoffset = stepoffset;
    }
    public Short getRampdir() {
        return this.rampdir;
    }
    
    public void setRampdir(Short rampdir) {
        this.rampdir = rampdir;
    }
    public Short getStimcycle() {
        return this.stimcycle;
    }
    
    public void setStimcycle(Short stimcycle) {
        this.stimcycle = stimcycle;
    }
    public Short getFramenum() {
        return this.framenum;
    }
    
    public void setFramenum(Short framenum) {
        this.framenum = framenum;
    }
    public short getChannum() {
        return this.channum;
    }
    
    public void setChannum(short channum) {
        this.channum = channum;
    }
    public short getDcenum() {
        return this.dcenum;
    }
    
    public void setDcenum(short dcenum) {
        this.dcenum = dcenum;
    }
    public Short getFowlernum() {
        return this.fowlernum;
    }
    
    public void setFowlernum(Short fowlernum) {
        this.fowlernum = fowlernum;
    }
    public Integer getWaitperiod() {
        return this.waitperiod;
    }
    
    public void setWaitperiod(Integer waitperiod) {
        this.waitperiod = waitperiod;
    }
    public Double getRaj2000predict() {
        return this.raj2000predict;
    }
    
    public void setRaj2000predict(Double raj2000predict) {
        this.raj2000predict = raj2000predict;
    }
    public Double getDecj2000predict() {
        return this.decj2000predict;
    }
    
    public void setDecj2000predict(Double decj2000predict) {
        this.decj2000predict = decj2000predict;
    }
    public Double getRaj2000reference() {
        return this.raj2000reference;
    }
    
    public void setRaj2000reference(Double raj2000reference) {
        this.raj2000reference = raj2000reference;
    }
    public Double getDecj2000reference() {
        return this.decj2000reference;
    }
    
    public void setDecj2000reference(Double decj2000reference) {
        this.decj2000reference = decj2000reference;
    }
    public Double getPosanglereference() {
        return this.posanglereference;
    }
    
    public void setPosanglereference(Double posanglereference) {
        this.posanglereference = posanglereference;
    }
    public Double getRaicrsactual() {
        return this.raicrsactual;
    }
    
    public void setRaicrsactual(Double raicrsactual) {
        this.raicrsactual = raicrsactual;
    }
    public Double getDecicrsactual() {
        return this.decicrsactual;
    }
    
    public void setDecicrsactual(Double decicrsactual) {
        this.decicrsactual = decicrsactual;
    }
    public Double getPosangleactual() {
        return this.posangleactual;
    }
    
    public void setPosangleactual(Double posangleactual) {
        this.posangleactual = posangleactual;
    }
    public Integer getPtgftid() {
        return this.ptgftid;
    }
    
    public void setPtgftid(Integer ptgftid) {
        this.ptgftid = ptgftid;
    }
    public Short getNumptgfiles() {
        return this.numptgfiles;
    }
    
    public void setNumptgfiles(Short numptgfiles) {
        this.numptgfiles = numptgfiles;
    }
    public Double getSclk() {
        return this.sclk;
    }
    
    public void setSclk(Double sclk) {
        this.sclk = sclk;
    }
    public Date getScet() {
        return this.scet;
    }
    
    public void setScet(Date scet) {
        this.scet = scet;
    }
    public String getInstrument() {
        return this.instrument;
    }
    
    public void setInstrument(String instrument) {
        this.instrument = instrument;
    }
    public Short getInitplscriptid() {
        return this.initplscriptid;
    }
    
    public void setInitplscriptid(Short initplscriptid) {
        this.initplscriptid = initplscriptid;
    }
    public Double getFrametime() {
        return this.frametime;
    }
    
    public void setFrametime(Double frametime) {
        this.frametime = frametime;
    }
    public Double getExposuretime() {
        return this.exposuretime;
    }
    
    public void setExposuretime(Double exposuretime) {
        this.exposuretime = exposuretime;
    }
    public Float getCompressratio() {
        return this.compressratio;
    }
    
    public void setCompressratio(Float compressratio) {
        this.compressratio = compressratio;
    }
    public short getPrimaryfield() {
        return this.primaryfield;
    }
    
    public void setPrimaryfield(short primaryfield) {
        this.primaryfield = primaryfield;
    }
    public Short getDefaultplscriptid() {
        return this.defaultplscriptid;
    }
    
    public void setDefaultplscriptid(Short defaultplscriptid) {
        this.defaultplscriptid = defaultplscriptid;
    }
    public Double getScanmirrordac() {
        return this.scanmirrordac;
    }
    
    public void setScanmirrordac(Double scanmirrordac) {
        this.scanmirrordac = scanmirrordac;
    }
    public Double getScanmirroraxisangledegrees() {
        return this.scanmirroraxisangledegrees;
    }
    
    public void setScanmirroraxisangledegrees(Double scanmirroraxisangledegrees) {
        this.scanmirroraxisangledegrees = scanmirroraxisangledegrees;
    }
    public Integer getDceinsid() {
        return this.dceinsid;
    }
    
    public void setDceinsid(Integer dceinsid) {
        this.dceinsid = dceinsid;
    }
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }
    public Date getReceivedat() {
        return this.receivedat;
    }
    
    public void setReceivedat(Date receivedat) {
        this.receivedat = receivedat;
    }
    public Short getDatamissing() {
        return this.datamissing;
    }
    
    public void setDatamissing(Short datamissing) {
        this.datamissing = datamissing;
    }
    public Short getLinesmissing() {
        return this.linesmissing;
    }
    
    public void setLinesmissing(Short linesmissing) {
        this.linesmissing = linesmissing;
    }
    public Short getPercentmissing() {
        return this.percentmissing;
    }
    
    public void setPercentmissing(Short percentmissing) {
        this.percentmissing = percentmissing;
    }
    public Short getAncilmissing() {
        return this.ancilmissing;
    }
    
    public void setAncilmissing(Short ancilmissing) {
        this.ancilmissing = ancilmissing;
    }
    public String getExternalname() {
        return this.externalname;
    }
    
    public void setExternalname(String externalname) {
        this.externalname = externalname;
    }
    public Integer getFilesize() {
        return this.filesize;
    }
    
    public void setFilesize(Integer filesize) {
        this.filesize = filesize;
    }




}


