package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * DceSetsId generated by hbm2java
 */
public class DceSetsId  implements java.io.Serializable {


     private int dcesetid;
     private int dceid;

    public DceSetsId() {
    }

    public DceSetsId(int dcesetid, int dceid) {
       this.dcesetid = dcesetid;
       this.dceid = dceid;
    }
   
    public int getDcesetid() {
        return this.dcesetid;
    }
    
    public void setDcesetid(int dcesetid) {
        this.dcesetid = dcesetid;
    }
    public int getDceid() {
        return this.dceid;
    }
    
    public void setDceid(int dceid) {
        this.dceid = dceid;
    }




}


