package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * DceSets generated by hbm2java
 */
public class DceSets  implements java.io.Serializable {


     private DceSetsId id;
     private DceInformation dceinformation;

    public DceSets() {
    }

    public DceSets(DceSetsId id, DceInformation dceinformation) {
       this.id = id;
       this.dceinformation = dceinformation;
    }
   
    public DceSetsId getId() {
        return this.id;
    }
    
    public void setId(DceSetsId id) {
        this.id = id;
    }
    public DceInformation getDceinformation() {
        return this.dceinformation;
    }
    
    public void setDceinformation(DceInformation dceinformation) {
        this.dceinformation = dceinformation;
    }




}


