package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * EnsembleSets generated by hbm2java
 */
public class EnsembleSets  implements java.io.Serializable {


     private EnsembleSetsId id;

    public EnsembleSets() {
    }

    public EnsembleSets(EnsembleSetsId id) {
       this.id = id;
    }
   
    public EnsembleSetsId getId() {
        return this.id;
    }
    
    public void setId(EnsembleSetsId id) {
        this.id = id;
    }




}


