package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * EnsembleSetsId generated by hbm2java
 */
public class EnsembleSetsId  implements java.io.Serializable {


     private int inensid;
     private int outensid;

    public EnsembleSetsId() {
    }

    public EnsembleSetsId(int inensid, int outensid) {
       this.inensid = inensid;
       this.outensid = outensid;
    }
   
    public int getInensid() {
        return this.inensid;
    }
    
    public void setInensid(int inensid) {
        this.inensid = inensid;
    }
    public int getOutensid() {
        return this.outensid;
    }
    
    public void setOutensid(int outensid) {
        this.outensid = outensid;
    }




}


