package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * IracMapPC generated by hbm2java
 */
public class IracMapPC  implements java.io.Serializable {


     private int reqkey;
     private RequestInformation requestinformation;
     private short readoutfull;
     private String ditherpat;
     private String ditherscale;
     private short array36;
     private short array45;
     private short datacollect36;
     private short datacollect45;
     private short highdynamic;
     private Float frametime;
     private Short nframes;
     private Short depth;
     private Short startcycleid;
     private short ismapping;
     private Short numcols;
     private Short numrows;
     private Float colstepsize;
     private Float rowstepsize;
     private Float columnoffset;
     private Float rowoffset;
     private String orient;
     private Float angle;
     private Short ncycles;
     private Boolean isrectangular;
     private Float hexstepsize;
     private Float hextilesize;

    public IracMapPC() {
    }

	
    public IracMapPC(int reqkey, RequestInformation requestinformation, short readoutfull, short array36, short array45, short datacollect36, short datacollect45, short highdynamic, short ismapping) {
        this.reqkey = reqkey;
        this.requestinformation = requestinformation;
        this.readoutfull = readoutfull;
        this.array36 = array36;
        this.array45 = array45;
        this.datacollect36 = datacollect36;
        this.datacollect45 = datacollect45;
        this.highdynamic = highdynamic;
        this.ismapping = ismapping;
    }
    public IracMapPC(int reqkey, RequestInformation requestinformation, short readoutfull, String ditherpat, String ditherscale, short array36, short array45, short datacollect36, short datacollect45, short highdynamic, Float frametime, Short nframes, Short depth, Short startcycleid, short ismapping, Short numcols, Short numrows, Float colstepsize, Float rowstepsize, Float columnoffset, Float rowoffset, String orient, Float angle, Short ncycles, Boolean isrectangular, Float hexstepsize, Float hextilesize) {
       this.reqkey = reqkey;
       this.requestinformation = requestinformation;
       this.readoutfull = readoutfull;
       this.ditherpat = ditherpat;
       this.ditherscale = ditherscale;
       this.array36 = array36;
       this.array45 = array45;
       this.datacollect36 = datacollect36;
       this.datacollect45 = datacollect45;
       this.highdynamic = highdynamic;
       this.frametime = frametime;
       this.nframes = nframes;
       this.depth = depth;
       this.startcycleid = startcycleid;
       this.ismapping = ismapping;
       this.numcols = numcols;
       this.numrows = numrows;
       this.colstepsize = colstepsize;
       this.rowstepsize = rowstepsize;
       this.columnoffset = columnoffset;
       this.rowoffset = rowoffset;
       this.orient = orient;
       this.angle = angle;
       this.ncycles = ncycles;
       this.isrectangular = isrectangular;
       this.hexstepsize = hexstepsize;
       this.hextilesize = hextilesize;
    }
   
    public int getReqkey() {
        return this.reqkey;
    }
    
    public void setReqkey(int reqkey) {
        this.reqkey = reqkey;
    }
    public RequestInformation getRequestinformation() {
        return this.requestinformation;
    }
    
    public void setRequestinformation(RequestInformation requestinformation) {
        this.requestinformation = requestinformation;
    }
    public short getReadoutfull() {
        return this.readoutfull;
    }
    
    public void setReadoutfull(short readoutfull) {
        this.readoutfull = readoutfull;
    }
    public String getDitherpat() {
        return this.ditherpat;
    }
    
    public void setDitherpat(String ditherpat) {
        this.ditherpat = ditherpat;
    }
    public String getDitherscale() {
        return this.ditherscale;
    }
    
    public void setDitherscale(String ditherscale) {
        this.ditherscale = ditherscale;
    }
    public short getArray36() {
        return this.array36;
    }
    
    public void setArray36(short array36) {
        this.array36 = array36;
    }
    public short getArray45() {
        return this.array45;
    }
    
    public void setArray45(short array45) {
        this.array45 = array45;
    }
    public short getDatacollect36() {
        return this.datacollect36;
    }
    
    public void setDatacollect36(short datacollect36) {
        this.datacollect36 = datacollect36;
    }
    public short getDatacollect45() {
        return this.datacollect45;
    }
    
    public void setDatacollect45(short datacollect45) {
        this.datacollect45 = datacollect45;
    }
    public short getHighdynamic() {
        return this.highdynamic;
    }
    
    public void setHighdynamic(short highdynamic) {
        this.highdynamic = highdynamic;
    }
    public Float getFrametime() {
        return this.frametime;
    }
    
    public void setFrametime(Float frametime) {
        this.frametime = frametime;
    }
    public Short getNframes() {
        return this.nframes;
    }
    
    public void setNframes(Short nframes) {
        this.nframes = nframes;
    }
    public Short getDepth() {
        return this.depth;
    }
    
    public void setDepth(Short depth) {
        this.depth = depth;
    }
    public Short getStartcycleid() {
        return this.startcycleid;
    }
    
    public void setStartcycleid(Short startcycleid) {
        this.startcycleid = startcycleid;
    }
    public short getIsmapping() {
        return this.ismapping;
    }
    
    public void setIsmapping(short ismapping) {
        this.ismapping = ismapping;
    }
    public Short getNumcols() {
        return this.numcols;
    }
    
    public void setNumcols(Short numcols) {
        this.numcols = numcols;
    }
    public Short getNumrows() {
        return this.numrows;
    }
    
    public void setNumrows(Short numrows) {
        this.numrows = numrows;
    }
    public Float getColstepsize() {
        return this.colstepsize;
    }
    
    public void setColstepsize(Float colstepsize) {
        this.colstepsize = colstepsize;
    }
    public Float getRowstepsize() {
        return this.rowstepsize;
    }
    
    public void setRowstepsize(Float rowstepsize) {
        this.rowstepsize = rowstepsize;
    }
    public Float getColumnoffset() {
        return this.columnoffset;
    }
    
    public void setColumnoffset(Float columnoffset) {
        this.columnoffset = columnoffset;
    }
    public Float getRowoffset() {
        return this.rowoffset;
    }
    
    public void setRowoffset(Float rowoffset) {
        this.rowoffset = rowoffset;
    }
    public String getOrient() {
        return this.orient;
    }
    
    public void setOrient(String orient) {
        this.orient = orient;
    }
    public Float getAngle() {
        return this.angle;
    }
    
    public void setAngle(Float angle) {
        this.angle = angle;
    }
    public Short getNcycles() {
        return this.ncycles;
    }
    
    public void setNcycles(Short ncycles) {
        this.ncycles = ncycles;
    }
    public Boolean getIsrectangular() {
        return this.isrectangular;
    }
    
    public void setIsrectangular(Boolean isrectangular) {
        this.isrectangular = isrectangular;
    }
    public Float getHexstepsize() {
        return this.hexstepsize;
    }
    
    public void setHexstepsize(Float hexstepsize) {
        this.hexstepsize = hexstepsize;
    }
    public Float getHextilesize() {
        return this.hextilesize;
    }
    
    public void setHextilesize(Float hextilesize) {
        this.hextilesize = hextilesize;
    }




}


