package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * IrsMap generated by hbm2java
 */
public class IrsMap  implements java.io.Serializable {


     private int reqkey;
     private RequestInformation requestinformation;
     private Short mapcycles;
     private short hisSelected;
     private Short hisExptime;
     private Short hisNumpointingspara;
     private Float hisStepsizepara;
     private Short hisNumpointingsperp;
     private Float hisStepsizeperp;
     private Short hisNumcycles;
     private short hilSelected;
     private Short hilExptime;
     private Short hilNumpointingspara;
     private Float hilStepsizepara;
     private Short hilNumpointingsperp;
     private Float hilStepsizeperp;
     private Short hilNumcycles;
     private short losSelected;
     private Short losExptime;
     private Short losNumpointingspara;
     private Float losStepsizepara;
     private Short losNumpointingsperp;
     private Float losStepsizeperp;
     private Short losNumcycles;
     private short lolSelected;
     private Short lolExptime;
     private Short lolNumpointingspara;
     private Float lolStepsizepara;
     private Short lolNumpointingsperp;
     private Float lolStepsizeperp;
     private Short lolNumcycles;
     private short lo5Selected;
     private Short lo5Exptime;
     private Short lo5Numpointingspara;
     private Float lo5Stepsizepara;
     private Short lo5Numpointingsperp;
     private Float lo5Stepsizeperp;
     private Short lo5Numcycles;
     private short lo7Selected;
     private Short lo7Exptime;
     private Short lo7Numpointingspara;
     private Float lo7Stepsizepara;
     private Short lo7Numpointingsperp;
     private Float lo7Stepsizeperp;
     private Short lo7Numcycles;
     private short lo14Selected;
     private Short lo14Exptime;
     private Short lo14Numpointingspara;
     private Float lo14Stepsizepara;
     private Short lo14Numpointingsperp;
     private Float lo14Stepsizeperp;
     private Short lo14Numcycles;
     private short lo21Selected;
     private Short lo21Exptime;
     private Short lo21Numpointingspara;
     private Float lo21Stepsizepara;
     private Short lo21Numpointingsperp;
     private Float lo21Stepsizeperp;
     private Short lo21Numcycles;
     private String peakupmode;
     private String peakupaccuracy;
     private String peakupfilter;
     private Float peakupfluxd;
     private short extendpksource;
     private short ispeakupposition;
     private Float offsetraj2000;
     private Float offsetdecj2000;
     private Double positionraj2000;
     private Double positiondecj2000;
     private Float posrapmj2000;
     private Float posdecpmj2000;
     private String lat;
     private String lon;
     private Float epoch;
     private short isbackgroundaor;

    public IrsMap() {
    }

	
    public IrsMap(int reqkey, RequestInformation requestinformation, short hisSelected, short hilSelected, short losSelected, short lolSelected, short lo5Selected, short lo7Selected, short lo14Selected, short lo21Selected, short extendpksource, short ispeakupposition, short isbackgroundaor) {
        this.reqkey = reqkey;
        this.requestinformation = requestinformation;
        this.hisSelected = hisSelected;
        this.hilSelected = hilSelected;
        this.losSelected = losSelected;
        this.lolSelected = lolSelected;
        this.lo5Selected = lo5Selected;
        this.lo7Selected = lo7Selected;
        this.lo14Selected = lo14Selected;
        this.lo21Selected = lo21Selected;
        this.extendpksource = extendpksource;
        this.ispeakupposition = ispeakupposition;
        this.isbackgroundaor = isbackgroundaor;
    }
    public IrsMap(int reqkey, RequestInformation requestinformation, Short mapcycles, short hisSelected, Short hisExptime, Short hisNumpointingspara, Float hisStepsizepara, Short hisNumpointingsperp, Float hisStepsizeperp, Short hisNumcycles, short hilSelected, Short hilExptime, Short hilNumpointingspara, Float hilStepsizepara, Short hilNumpointingsperp, Float hilStepsizeperp, Short hilNumcycles, short losSelected, Short losExptime, Short losNumpointingspara, Float losStepsizepara, Short losNumpointingsperp, Float losStepsizeperp, Short losNumcycles, short lolSelected, Short lolExptime, Short lolNumpointingspara, Float lolStepsizepara, Short lolNumpointingsperp, Float lolStepsizeperp, Short lolNumcycles, short lo5Selected, Short lo5Exptime, Short lo5Numpointingspara, Float lo5Stepsizepara, Short lo5Numpointingsperp, Float lo5Stepsizeperp, Short lo5Numcycles, short lo7Selected, Short lo7Exptime, Short lo7Numpointingspara, Float lo7Stepsizepara, Short lo7Numpointingsperp, Float lo7Stepsizeperp, Short lo7Numcycles, short lo14Selected, Short lo14Exptime, Short lo14Numpointingspara, Float lo14Stepsizepara, Short lo14Numpointingsperp, Float lo14Stepsizeperp, Short lo14Numcycles, short lo21Selected, Short lo21Exptime, Short lo21Numpointingspara, Float lo21Stepsizepara, Short lo21Numpointingsperp, Float lo21Stepsizeperp, Short lo21Numcycles, String peakupmode, String peakupaccuracy, String peakupfilter, Float peakupfluxd, short extendpksource, short ispeakupposition, Float offsetraj2000, Float offsetdecj2000, Double positionraj2000, Double positiondecj2000, Float posrapmj2000, Float posdecpmj2000, String lat, String lon, Float epoch, short isbackgroundaor) {
       this.reqkey = reqkey;
       this.requestinformation = requestinformation;
       this.mapcycles = mapcycles;
       this.hisSelected = hisSelected;
       this.hisExptime = hisExptime;
       this.hisNumpointingspara = hisNumpointingspara;
       this.hisStepsizepara = hisStepsizepara;
       this.hisNumpointingsperp = hisNumpointingsperp;
       this.hisStepsizeperp = hisStepsizeperp;
       this.hisNumcycles = hisNumcycles;
       this.hilSelected = hilSelected;
       this.hilExptime = hilExptime;
       this.hilNumpointingspara = hilNumpointingspara;
       this.hilStepsizepara = hilStepsizepara;
       this.hilNumpointingsperp = hilNumpointingsperp;
       this.hilStepsizeperp = hilStepsizeperp;
       this.hilNumcycles = hilNumcycles;
       this.losSelected = losSelected;
       this.losExptime = losExptime;
       this.losNumpointingspara = losNumpointingspara;
       this.losStepsizepara = losStepsizepara;
       this.losNumpointingsperp = losNumpointingsperp;
       this.losStepsizeperp = losStepsizeperp;
       this.losNumcycles = losNumcycles;
       this.lolSelected = lolSelected;
       this.lolExptime = lolExptime;
       this.lolNumpointingspara = lolNumpointingspara;
       this.lolStepsizepara = lolStepsizepara;
       this.lolNumpointingsperp = lolNumpointingsperp;
       this.lolStepsizeperp = lolStepsizeperp;
       this.lolNumcycles = lolNumcycles;
       this.lo5Selected = lo5Selected;
       this.lo5Exptime = lo5Exptime;
       this.lo5Numpointingspara = lo5Numpointingspara;
       this.lo5Stepsizepara = lo5Stepsizepara;
       this.lo5Numpointingsperp = lo5Numpointingsperp;
       this.lo5Stepsizeperp = lo5Stepsizeperp;
       this.lo5Numcycles = lo5Numcycles;
       this.lo7Selected = lo7Selected;
       this.lo7Exptime = lo7Exptime;
       this.lo7Numpointingspara = lo7Numpointingspara;
       this.lo7Stepsizepara = lo7Stepsizepara;
       this.lo7Numpointingsperp = lo7Numpointingsperp;
       this.lo7Stepsizeperp = lo7Stepsizeperp;
       this.lo7Numcycles = lo7Numcycles;
       this.lo14Selected = lo14Selected;
       this.lo14Exptime = lo14Exptime;
       this.lo14Numpointingspara = lo14Numpointingspara;
       this.lo14Stepsizepara = lo14Stepsizepara;
       this.lo14Numpointingsperp = lo14Numpointingsperp;
       this.lo14Stepsizeperp = lo14Stepsizeperp;
       this.lo14Numcycles = lo14Numcycles;
       this.lo21Selected = lo21Selected;
       this.lo21Exptime = lo21Exptime;
       this.lo21Numpointingspara = lo21Numpointingspara;
       this.lo21Stepsizepara = lo21Stepsizepara;
       this.lo21Numpointingsperp = lo21Numpointingsperp;
       this.lo21Stepsizeperp = lo21Stepsizeperp;
       this.lo21Numcycles = lo21Numcycles;
       this.peakupmode = peakupmode;
       this.peakupaccuracy = peakupaccuracy;
       this.peakupfilter = peakupfilter;
       this.peakupfluxd = peakupfluxd;
       this.extendpksource = extendpksource;
       this.ispeakupposition = ispeakupposition;
       this.offsetraj2000 = offsetraj2000;
       this.offsetdecj2000 = offsetdecj2000;
       this.positionraj2000 = positionraj2000;
       this.positiondecj2000 = positiondecj2000;
       this.posrapmj2000 = posrapmj2000;
       this.posdecpmj2000 = posdecpmj2000;
       this.lat = lat;
       this.lon = lon;
       this.epoch = epoch;
       this.isbackgroundaor = isbackgroundaor;
    }
   
    public int getReqkey() {
        return this.reqkey;
    }
    
    public void setReqkey(int reqkey) {
        this.reqkey = reqkey;
    }
    public RequestInformation getRequestinformation() {
        return this.requestinformation;
    }
    
    public void setRequestinformation(RequestInformation requestinformation) {
        this.requestinformation = requestinformation;
    }
    public Short getMapcycles() {
        return this.mapcycles;
    }
    
    public void setMapcycles(Short mapcycles) {
        this.mapcycles = mapcycles;
    }
    public short getHisSelected() {
        return this.hisSelected;
    }
    
    public void setHisSelected(short hisSelected) {
        this.hisSelected = hisSelected;
    }
    public Short getHisExptime() {
        return this.hisExptime;
    }
    
    public void setHisExptime(Short hisExptime) {
        this.hisExptime = hisExptime;
    }
    public Short getHisNumpointingspara() {
        return this.hisNumpointingspara;
    }
    
    public void setHisNumpointingspara(Short hisNumpointingspara) {
        this.hisNumpointingspara = hisNumpointingspara;
    }
    public Float getHisStepsizepara() {
        return this.hisStepsizepara;
    }
    
    public void setHisStepsizepara(Float hisStepsizepara) {
        this.hisStepsizepara = hisStepsizepara;
    }
    public Short getHisNumpointingsperp() {
        return this.hisNumpointingsperp;
    }
    
    public void setHisNumpointingsperp(Short hisNumpointingsperp) {
        this.hisNumpointingsperp = hisNumpointingsperp;
    }
    public Float getHisStepsizeperp() {
        return this.hisStepsizeperp;
    }
    
    public void setHisStepsizeperp(Float hisStepsizeperp) {
        this.hisStepsizeperp = hisStepsizeperp;
    }
    public Short getHisNumcycles() {
        return this.hisNumcycles;
    }
    
    public void setHisNumcycles(Short hisNumcycles) {
        this.hisNumcycles = hisNumcycles;
    }
    public short getHilSelected() {
        return this.hilSelected;
    }
    
    public void setHilSelected(short hilSelected) {
        this.hilSelected = hilSelected;
    }
    public Short getHilExptime() {
        return this.hilExptime;
    }
    
    public void setHilExptime(Short hilExptime) {
        this.hilExptime = hilExptime;
    }
    public Short getHilNumpointingspara() {
        return this.hilNumpointingspara;
    }
    
    public void setHilNumpointingspara(Short hilNumpointingspara) {
        this.hilNumpointingspara = hilNumpointingspara;
    }
    public Float getHilStepsizepara() {
        return this.hilStepsizepara;
    }
    
    public void setHilStepsizepara(Float hilStepsizepara) {
        this.hilStepsizepara = hilStepsizepara;
    }
    public Short getHilNumpointingsperp() {
        return this.hilNumpointingsperp;
    }
    
    public void setHilNumpointingsperp(Short hilNumpointingsperp) {
        this.hilNumpointingsperp = hilNumpointingsperp;
    }
    public Float getHilStepsizeperp() {
        return this.hilStepsizeperp;
    }
    
    public void setHilStepsizeperp(Float hilStepsizeperp) {
        this.hilStepsizeperp = hilStepsizeperp;
    }
    public Short getHilNumcycles() {
        return this.hilNumcycles;
    }
    
    public void setHilNumcycles(Short hilNumcycles) {
        this.hilNumcycles = hilNumcycles;
    }
    public short getLosSelected() {
        return this.losSelected;
    }
    
    public void setLosSelected(short losSelected) {
        this.losSelected = losSelected;
    }
    public Short getLosExptime() {
        return this.losExptime;
    }
    
    public void setLosExptime(Short losExptime) {
        this.losExptime = losExptime;
    }
    public Short getLosNumpointingspara() {
        return this.losNumpointingspara;
    }
    
    public void setLosNumpointingspara(Short losNumpointingspara) {
        this.losNumpointingspara = losNumpointingspara;
    }
    public Float getLosStepsizepara() {
        return this.losStepsizepara;
    }
    
    public void setLosStepsizepara(Float losStepsizepara) {
        this.losStepsizepara = losStepsizepara;
    }
    public Short getLosNumpointingsperp() {
        return this.losNumpointingsperp;
    }
    
    public void setLosNumpointingsperp(Short losNumpointingsperp) {
        this.losNumpointingsperp = losNumpointingsperp;
    }
    public Float getLosStepsizeperp() {
        return this.losStepsizeperp;
    }
    
    public void setLosStepsizeperp(Float losStepsizeperp) {
        this.losStepsizeperp = losStepsizeperp;
    }
    public Short getLosNumcycles() {
        return this.losNumcycles;
    }
    
    public void setLosNumcycles(Short losNumcycles) {
        this.losNumcycles = losNumcycles;
    }
    public short getLolSelected() {
        return this.lolSelected;
    }
    
    public void setLolSelected(short lolSelected) {
        this.lolSelected = lolSelected;
    }
    public Short getLolExptime() {
        return this.lolExptime;
    }
    
    public void setLolExptime(Short lolExptime) {
        this.lolExptime = lolExptime;
    }
    public Short getLolNumpointingspara() {
        return this.lolNumpointingspara;
    }
    
    public void setLolNumpointingspara(Short lolNumpointingspara) {
        this.lolNumpointingspara = lolNumpointingspara;
    }
    public Float getLolStepsizepara() {
        return this.lolStepsizepara;
    }
    
    public void setLolStepsizepara(Float lolStepsizepara) {
        this.lolStepsizepara = lolStepsizepara;
    }
    public Short getLolNumpointingsperp() {
        return this.lolNumpointingsperp;
    }
    
    public void setLolNumpointingsperp(Short lolNumpointingsperp) {
        this.lolNumpointingsperp = lolNumpointingsperp;
    }
    public Float getLolStepsizeperp() {
        return this.lolStepsizeperp;
    }
    
    public void setLolStepsizeperp(Float lolStepsizeperp) {
        this.lolStepsizeperp = lolStepsizeperp;
    }
    public Short getLolNumcycles() {
        return this.lolNumcycles;
    }
    
    public void setLolNumcycles(Short lolNumcycles) {
        this.lolNumcycles = lolNumcycles;
    }
    public short getLo5Selected() {
        return this.lo5Selected;
    }
    
    public void setLo5Selected(short lo5Selected) {
        this.lo5Selected = lo5Selected;
    }
    public Short getLo5Exptime() {
        return this.lo5Exptime;
    }
    
    public void setLo5Exptime(Short lo5Exptime) {
        this.lo5Exptime = lo5Exptime;
    }
    public Short getLo5Numpointingspara() {
        return this.lo5Numpointingspara;
    }
    
    public void setLo5Numpointingspara(Short lo5Numpointingspara) {
        this.lo5Numpointingspara = lo5Numpointingspara;
    }
    public Float getLo5Stepsizepara() {
        return this.lo5Stepsizepara;
    }
    
    public void setLo5Stepsizepara(Float lo5Stepsizepara) {
        this.lo5Stepsizepara = lo5Stepsizepara;
    }
    public Short getLo5Numpointingsperp() {
        return this.lo5Numpointingsperp;
    }
    
    public void setLo5Numpointingsperp(Short lo5Numpointingsperp) {
        this.lo5Numpointingsperp = lo5Numpointingsperp;
    }
    public Float getLo5Stepsizeperp() {
        return this.lo5Stepsizeperp;
    }
    
    public void setLo5Stepsizeperp(Float lo5Stepsizeperp) {
        this.lo5Stepsizeperp = lo5Stepsizeperp;
    }
    public Short getLo5Numcycles() {
        return this.lo5Numcycles;
    }
    
    public void setLo5Numcycles(Short lo5Numcycles) {
        this.lo5Numcycles = lo5Numcycles;
    }
    public short getLo7Selected() {
        return this.lo7Selected;
    }
    
    public void setLo7Selected(short lo7Selected) {
        this.lo7Selected = lo7Selected;
    }
    public Short getLo7Exptime() {
        return this.lo7Exptime;
    }
    
    public void setLo7Exptime(Short lo7Exptime) {
        this.lo7Exptime = lo7Exptime;
    }
    public Short getLo7Numpointingspara() {
        return this.lo7Numpointingspara;
    }
    
    public void setLo7Numpointingspara(Short lo7Numpointingspara) {
        this.lo7Numpointingspara = lo7Numpointingspara;
    }
    public Float getLo7Stepsizepara() {
        return this.lo7Stepsizepara;
    }
    
    public void setLo7Stepsizepara(Float lo7Stepsizepara) {
        this.lo7Stepsizepara = lo7Stepsizepara;
    }
    public Short getLo7Numpointingsperp() {
        return this.lo7Numpointingsperp;
    }
    
    public void setLo7Numpointingsperp(Short lo7Numpointingsperp) {
        this.lo7Numpointingsperp = lo7Numpointingsperp;
    }
    public Float getLo7Stepsizeperp() {
        return this.lo7Stepsizeperp;
    }
    
    public void setLo7Stepsizeperp(Float lo7Stepsizeperp) {
        this.lo7Stepsizeperp = lo7Stepsizeperp;
    }
    public Short getLo7Numcycles() {
        return this.lo7Numcycles;
    }
    
    public void setLo7Numcycles(Short lo7Numcycles) {
        this.lo7Numcycles = lo7Numcycles;
    }
    public short getLo14Selected() {
        return this.lo14Selected;
    }
    
    public void setLo14Selected(short lo14Selected) {
        this.lo14Selected = lo14Selected;
    }
    public Short getLo14Exptime() {
        return this.lo14Exptime;
    }
    
    public void setLo14Exptime(Short lo14Exptime) {
        this.lo14Exptime = lo14Exptime;
    }
    public Short getLo14Numpointingspara() {
        return this.lo14Numpointingspara;
    }
    
    public void setLo14Numpointingspara(Short lo14Numpointingspara) {
        this.lo14Numpointingspara = lo14Numpointingspara;
    }
    public Float getLo14Stepsizepara() {
        return this.lo14Stepsizepara;
    }
    
    public void setLo14Stepsizepara(Float lo14Stepsizepara) {
        this.lo14Stepsizepara = lo14Stepsizepara;
    }
    public Short getLo14Numpointingsperp() {
        return this.lo14Numpointingsperp;
    }
    
    public void setLo14Numpointingsperp(Short lo14Numpointingsperp) {
        this.lo14Numpointingsperp = lo14Numpointingsperp;
    }
    public Float getLo14Stepsizeperp() {
        return this.lo14Stepsizeperp;
    }
    
    public void setLo14Stepsizeperp(Float lo14Stepsizeperp) {
        this.lo14Stepsizeperp = lo14Stepsizeperp;
    }
    public Short getLo14Numcycles() {
        return this.lo14Numcycles;
    }
    
    public void setLo14Numcycles(Short lo14Numcycles) {
        this.lo14Numcycles = lo14Numcycles;
    }
    public short getLo21Selected() {
        return this.lo21Selected;
    }
    
    public void setLo21Selected(short lo21Selected) {
        this.lo21Selected = lo21Selected;
    }
    public Short getLo21Exptime() {
        return this.lo21Exptime;
    }
    
    public void setLo21Exptime(Short lo21Exptime) {
        this.lo21Exptime = lo21Exptime;
    }
    public Short getLo21Numpointingspara() {
        return this.lo21Numpointingspara;
    }
    
    public void setLo21Numpointingspara(Short lo21Numpointingspara) {
        this.lo21Numpointingspara = lo21Numpointingspara;
    }
    public Float getLo21Stepsizepara() {
        return this.lo21Stepsizepara;
    }
    
    public void setLo21Stepsizepara(Float lo21Stepsizepara) {
        this.lo21Stepsizepara = lo21Stepsizepara;
    }
    public Short getLo21Numpointingsperp() {
        return this.lo21Numpointingsperp;
    }
    
    public void setLo21Numpointingsperp(Short lo21Numpointingsperp) {
        this.lo21Numpointingsperp = lo21Numpointingsperp;
    }
    public Float getLo21Stepsizeperp() {
        return this.lo21Stepsizeperp;
    }
    
    public void setLo21Stepsizeperp(Float lo21Stepsizeperp) {
        this.lo21Stepsizeperp = lo21Stepsizeperp;
    }
    public Short getLo21Numcycles() {
        return this.lo21Numcycles;
    }
    
    public void setLo21Numcycles(Short lo21Numcycles) {
        this.lo21Numcycles = lo21Numcycles;
    }
    public String getPeakupmode() {
        return this.peakupmode;
    }
    
    public void setPeakupmode(String peakupmode) {
        this.peakupmode = peakupmode;
    }
    public String getPeakupaccuracy() {
        return this.peakupaccuracy;
    }
    
    public void setPeakupaccuracy(String peakupaccuracy) {
        this.peakupaccuracy = peakupaccuracy;
    }
    public String getPeakupfilter() {
        return this.peakupfilter;
    }
    
    public void setPeakupfilter(String peakupfilter) {
        this.peakupfilter = peakupfilter;
    }
    public Float getPeakupfluxd() {
        return this.peakupfluxd;
    }
    
    public void setPeakupfluxd(Float peakupfluxd) {
        this.peakupfluxd = peakupfluxd;
    }
    public short getExtendpksource() {
        return this.extendpksource;
    }
    
    public void setExtendpksource(short extendpksource) {
        this.extendpksource = extendpksource;
    }
    public short getIspeakupposition() {
        return this.ispeakupposition;
    }
    
    public void setIspeakupposition(short ispeakupposition) {
        this.ispeakupposition = ispeakupposition;
    }
    public Float getOffsetraj2000() {
        return this.offsetraj2000;
    }
    
    public void setOffsetraj2000(Float offsetraj2000) {
        this.offsetraj2000 = offsetraj2000;
    }
    public Float getOffsetdecj2000() {
        return this.offsetdecj2000;
    }
    
    public void setOffsetdecj2000(Float offsetdecj2000) {
        this.offsetdecj2000 = offsetdecj2000;
    }
    public Double getPositionraj2000() {
        return this.positionraj2000;
    }
    
    public void setPositionraj2000(Double positionraj2000) {
        this.positionraj2000 = positionraj2000;
    }
    public Double getPositiondecj2000() {
        return this.positiondecj2000;
    }
    
    public void setPositiondecj2000(Double positiondecj2000) {
        this.positiondecj2000 = positiondecj2000;
    }
    public Float getPosrapmj2000() {
        return this.posrapmj2000;
    }
    
    public void setPosrapmj2000(Float posrapmj2000) {
        this.posrapmj2000 = posrapmj2000;
    }
    public Float getPosdecpmj2000() {
        return this.posdecpmj2000;
    }
    
    public void setPosdecpmj2000(Float posdecpmj2000) {
        this.posdecpmj2000 = posdecpmj2000;
    }
    public String getLat() {
        return this.lat;
    }
    
    public void setLat(String lat) {
        this.lat = lat;
    }
    public String getLon() {
        return this.lon;
    }
    
    public void setLon(String lon) {
        this.lon = lon;
    }
    public Float getEpoch() {
        return this.epoch;
    }
    
    public void setEpoch(Float epoch) {
        this.epoch = epoch;
    }
    public short getIsbackgroundaor() {
        return this.isbackgroundaor;
    }
    
    public void setIsbackgroundaor(short isbackgroundaor) {
        this.isbackgroundaor = isbackgroundaor;
    }




}


