package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * IrsPeakupImage generated by hbm2java
 */
public class IrsPeakupImage  implements java.io.Serializable {


     private int reqkey;
     private RequestInformation requestinformation;
     private short redSelected;
     private Short redExptime;
     private Short redNumcycles;
     private short blueSelected;
     private Short blueExptime;
     private Short blueNumcycles;
     private short middleSelected;
     private Short middleExptime;
     private Short middleNumcycles;
     private short ismapping;
     private Short numcols;
     private Short numrows;
     private Float colstepsize;
     private Float rowstepsize;
     private Float columnoffset;
     private Float rowoffset;
     private String orient;
     private Float angle;
     private Short numcycles;
     private String ditherpat;
     private String ditherscale;
     private Short depth;
     private Short startcycleid;

    public IrsPeakupImage() {
    }

	
    public IrsPeakupImage(int reqkey, RequestInformation requestinformation, short redSelected, short blueSelected, short middleSelected, short ismapping) {
        this.reqkey = reqkey;
        this.requestinformation = requestinformation;
        this.redSelected = redSelected;
        this.blueSelected = blueSelected;
        this.middleSelected = middleSelected;
        this.ismapping = ismapping;
    }
    public IrsPeakupImage(int reqkey, RequestInformation requestinformation, short redSelected, Short redExptime, Short redNumcycles, short blueSelected, Short blueExptime, Short blueNumcycles, short middleSelected, Short middleExptime, Short middleNumcycles, short ismapping, Short numcols, Short numrows, Float colstepsize, Float rowstepsize, Float columnoffset, Float rowoffset, String orient, Float angle, Short numcycles, String ditherpat, String ditherscale, Short depth, Short startcycleid) {
       this.reqkey = reqkey;
       this.requestinformation = requestinformation;
       this.redSelected = redSelected;
       this.redExptime = redExptime;
       this.redNumcycles = redNumcycles;
       this.blueSelected = blueSelected;
       this.blueExptime = blueExptime;
       this.blueNumcycles = blueNumcycles;
       this.middleSelected = middleSelected;
       this.middleExptime = middleExptime;
       this.middleNumcycles = middleNumcycles;
       this.ismapping = ismapping;
       this.numcols = numcols;
       this.numrows = numrows;
       this.colstepsize = colstepsize;
       this.rowstepsize = rowstepsize;
       this.columnoffset = columnoffset;
       this.rowoffset = rowoffset;
       this.orient = orient;
       this.angle = angle;
       this.numcycles = numcycles;
       this.ditherpat = ditherpat;
       this.ditherscale = ditherscale;
       this.depth = depth;
       this.startcycleid = startcycleid;
    }
   
    public int getReqkey() {
        return this.reqkey;
    }
    
    public void setReqkey(int reqkey) {
        this.reqkey = reqkey;
    }
    public RequestInformation getRequestinformation() {
        return this.requestinformation;
    }
    
    public void setRequestinformation(RequestInformation requestinformation) {
        this.requestinformation = requestinformation;
    }
    public short getRedSelected() {
        return this.redSelected;
    }
    
    public void setRedSelected(short redSelected) {
        this.redSelected = redSelected;
    }
    public Short getRedExptime() {
        return this.redExptime;
    }
    
    public void setRedExptime(Short redExptime) {
        this.redExptime = redExptime;
    }
    public Short getRedNumcycles() {
        return this.redNumcycles;
    }
    
    public void setRedNumcycles(Short redNumcycles) {
        this.redNumcycles = redNumcycles;
    }
    public short getBlueSelected() {
        return this.blueSelected;
    }
    
    public void setBlueSelected(short blueSelected) {
        this.blueSelected = blueSelected;
    }
    public Short getBlueExptime() {
        return this.blueExptime;
    }
    
    public void setBlueExptime(Short blueExptime) {
        this.blueExptime = blueExptime;
    }
    public Short getBlueNumcycles() {
        return this.blueNumcycles;
    }
    
    public void setBlueNumcycles(Short blueNumcycles) {
        this.blueNumcycles = blueNumcycles;
    }
    public short getMiddleSelected() {
        return this.middleSelected;
    }
    
    public void setMiddleSelected(short middleSelected) {
        this.middleSelected = middleSelected;
    }
    public Short getMiddleExptime() {
        return this.middleExptime;
    }
    
    public void setMiddleExptime(Short middleExptime) {
        this.middleExptime = middleExptime;
    }
    public Short getMiddleNumcycles() {
        return this.middleNumcycles;
    }
    
    public void setMiddleNumcycles(Short middleNumcycles) {
        this.middleNumcycles = middleNumcycles;
    }
    public short getIsmapping() {
        return this.ismapping;
    }
    
    public void setIsmapping(short ismapping) {
        this.ismapping = ismapping;
    }
    public Short getNumcols() {
        return this.numcols;
    }
    
    public void setNumcols(Short numcols) {
        this.numcols = numcols;
    }
    public Short getNumrows() {
        return this.numrows;
    }
    
    public void setNumrows(Short numrows) {
        this.numrows = numrows;
    }
    public Float getColstepsize() {
        return this.colstepsize;
    }
    
    public void setColstepsize(Float colstepsize) {
        this.colstepsize = colstepsize;
    }
    public Float getRowstepsize() {
        return this.rowstepsize;
    }
    
    public void setRowstepsize(Float rowstepsize) {
        this.rowstepsize = rowstepsize;
    }
    public Float getColumnoffset() {
        return this.columnoffset;
    }
    
    public void setColumnoffset(Float columnoffset) {
        this.columnoffset = columnoffset;
    }
    public Float getRowoffset() {
        return this.rowoffset;
    }
    
    public void setRowoffset(Float rowoffset) {
        this.rowoffset = rowoffset;
    }
    public String getOrient() {
        return this.orient;
    }
    
    public void setOrient(String orient) {
        this.orient = orient;
    }
    public Float getAngle() {
        return this.angle;
    }
    
    public void setAngle(Float angle) {
        this.angle = angle;
    }
    public Short getNumcycles() {
        return this.numcycles;
    }
    
    public void setNumcycles(Short numcycles) {
        this.numcycles = numcycles;
    }
    public String getDitherpat() {
        return this.ditherpat;
    }
    
    public void setDitherpat(String ditherpat) {
        this.ditherpat = ditherpat;
    }
    public String getDitherscale() {
        return this.ditherscale;
    }
    
    public void setDitherscale(String ditherscale) {
        this.ditherscale = ditherscale;
    }
    public Short getDepth() {
        return this.depth;
    }
    
    public void setDepth(Short depth) {
        this.depth = depth;
    }
    public Short getStartcycleid() {
        return this.startcycleid;
    }
    
    public void setStartcycleid(Short startcycleid) {
        this.startcycleid = startcycleid;
    }




}


