package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * IrsStare generated by hbm2java
 */
public class IrsStare  implements java.io.Serializable {


     private int reqkey;
     private RequestInformation requestinformation;
     private short hi10Selected;
     private Short hi10Exptime;
     private Short hi10Numcycles;
     private short hi19Selected;
     private Short hi19Exptime;
     private Short hi19Numcycles;
     private short lo5Selected;
     private Short lo5Exptime;
     private Short lo5Numcycles;
     private short lo7Selected;
     private Short lo7Exptime;
     private Short lo7Numcycles;
     private short lo14Selected;
     private Short lo14Exptime;
     private Short lo14Numcycles;
     private short lo21Selected;
     private Short lo21Exptime;
     private Short lo21Numcycles;
     private String mode;
     private String peakupmode;
     private String peakupaccuracy;
     private String peakupfilter;
     private Float peakupfluxd;
     private short extendpksource;
     private short ispeakupposition;
     private Float offsetraj2000;
     private Float offsetdecj2000;
     private Double positionraj2000;
     private Double positiondecj2000;
     private Float posrapmj2000;
     private Float posdecpmj2000;
     private String lat;
     private String lon;
     private Float epoch;
     private short isbackgroundaor;

    public IrsStare() {
    }

	
    public IrsStare(int reqkey, RequestInformation requestinformation, short hi10Selected, short hi19Selected, short lo5Selected, short lo7Selected, short lo14Selected, short lo21Selected, short extendpksource, short ispeakupposition, short isbackgroundaor) {
        this.reqkey = reqkey;
        this.requestinformation = requestinformation;
        this.hi10Selected = hi10Selected;
        this.hi19Selected = hi19Selected;
        this.lo5Selected = lo5Selected;
        this.lo7Selected = lo7Selected;
        this.lo14Selected = lo14Selected;
        this.lo21Selected = lo21Selected;
        this.extendpksource = extendpksource;
        this.ispeakupposition = ispeakupposition;
        this.isbackgroundaor = isbackgroundaor;
    }
    public IrsStare(int reqkey, RequestInformation requestinformation, short hi10Selected, Short hi10Exptime, Short hi10Numcycles, short hi19Selected, Short hi19Exptime, Short hi19Numcycles, short lo5Selected, Short lo5Exptime, Short lo5Numcycles, short lo7Selected, Short lo7Exptime, Short lo7Numcycles, short lo14Selected, Short lo14Exptime, Short lo14Numcycles, short lo21Selected, Short lo21Exptime, Short lo21Numcycles, String mode, String peakupmode, String peakupaccuracy, String peakupfilter, Float peakupfluxd, short extendpksource, short ispeakupposition, Float offsetraj2000, Float offsetdecj2000, Double positionraj2000, Double positiondecj2000, Float posrapmj2000, Float posdecpmj2000, String lat, String lon, Float epoch, short isbackgroundaor) {
       this.reqkey = reqkey;
       this.requestinformation = requestinformation;
       this.hi10Selected = hi10Selected;
       this.hi10Exptime = hi10Exptime;
       this.hi10Numcycles = hi10Numcycles;
       this.hi19Selected = hi19Selected;
       this.hi19Exptime = hi19Exptime;
       this.hi19Numcycles = hi19Numcycles;
       this.lo5Selected = lo5Selected;
       this.lo5Exptime = lo5Exptime;
       this.lo5Numcycles = lo5Numcycles;
       this.lo7Selected = lo7Selected;
       this.lo7Exptime = lo7Exptime;
       this.lo7Numcycles = lo7Numcycles;
       this.lo14Selected = lo14Selected;
       this.lo14Exptime = lo14Exptime;
       this.lo14Numcycles = lo14Numcycles;
       this.lo21Selected = lo21Selected;
       this.lo21Exptime = lo21Exptime;
       this.lo21Numcycles = lo21Numcycles;
       this.mode = mode;
       this.peakupmode = peakupmode;
       this.peakupaccuracy = peakupaccuracy;
       this.peakupfilter = peakupfilter;
       this.peakupfluxd = peakupfluxd;
       this.extendpksource = extendpksource;
       this.ispeakupposition = ispeakupposition;
       this.offsetraj2000 = offsetraj2000;
       this.offsetdecj2000 = offsetdecj2000;
       this.positionraj2000 = positionraj2000;
       this.positiondecj2000 = positiondecj2000;
       this.posrapmj2000 = posrapmj2000;
       this.posdecpmj2000 = posdecpmj2000;
       this.lat = lat;
       this.lon = lon;
       this.epoch = epoch;
       this.isbackgroundaor = isbackgroundaor;
    }
   
    public int getReqkey() {
        return this.reqkey;
    }
    
    public void setReqkey(int reqkey) {
        this.reqkey = reqkey;
    }
    public RequestInformation getRequestinformation() {
        return this.requestinformation;
    }
    
    public void setRequestinformation(RequestInformation requestinformation) {
        this.requestinformation = requestinformation;
    }
    public short getHi10Selected() {
        return this.hi10Selected;
    }
    
    public void setHi10Selected(short hi10Selected) {
        this.hi10Selected = hi10Selected;
    }
    public Short getHi10Exptime() {
        return this.hi10Exptime;
    }
    
    public void setHi10Exptime(Short hi10Exptime) {
        this.hi10Exptime = hi10Exptime;
    }
    public Short getHi10Numcycles() {
        return this.hi10Numcycles;
    }
    
    public void setHi10Numcycles(Short hi10Numcycles) {
        this.hi10Numcycles = hi10Numcycles;
    }
    public short getHi19Selected() {
        return this.hi19Selected;
    }
    
    public void setHi19Selected(short hi19Selected) {
        this.hi19Selected = hi19Selected;
    }
    public Short getHi19Exptime() {
        return this.hi19Exptime;
    }
    
    public void setHi19Exptime(Short hi19Exptime) {
        this.hi19Exptime = hi19Exptime;
    }
    public Short getHi19Numcycles() {
        return this.hi19Numcycles;
    }
    
    public void setHi19Numcycles(Short hi19Numcycles) {
        this.hi19Numcycles = hi19Numcycles;
    }
    public short getLo5Selected() {
        return this.lo5Selected;
    }
    
    public void setLo5Selected(short lo5Selected) {
        this.lo5Selected = lo5Selected;
    }
    public Short getLo5Exptime() {
        return this.lo5Exptime;
    }
    
    public void setLo5Exptime(Short lo5Exptime) {
        this.lo5Exptime = lo5Exptime;
    }
    public Short getLo5Numcycles() {
        return this.lo5Numcycles;
    }
    
    public void setLo5Numcycles(Short lo5Numcycles) {
        this.lo5Numcycles = lo5Numcycles;
    }
    public short getLo7Selected() {
        return this.lo7Selected;
    }
    
    public void setLo7Selected(short lo7Selected) {
        this.lo7Selected = lo7Selected;
    }
    public Short getLo7Exptime() {
        return this.lo7Exptime;
    }
    
    public void setLo7Exptime(Short lo7Exptime) {
        this.lo7Exptime = lo7Exptime;
    }
    public Short getLo7Numcycles() {
        return this.lo7Numcycles;
    }
    
    public void setLo7Numcycles(Short lo7Numcycles) {
        this.lo7Numcycles = lo7Numcycles;
    }
    public short getLo14Selected() {
        return this.lo14Selected;
    }
    
    public void setLo14Selected(short lo14Selected) {
        this.lo14Selected = lo14Selected;
    }
    public Short getLo14Exptime() {
        return this.lo14Exptime;
    }
    
    public void setLo14Exptime(Short lo14Exptime) {
        this.lo14Exptime = lo14Exptime;
    }
    public Short getLo14Numcycles() {
        return this.lo14Numcycles;
    }
    
    public void setLo14Numcycles(Short lo14Numcycles) {
        this.lo14Numcycles = lo14Numcycles;
    }
    public short getLo21Selected() {
        return this.lo21Selected;
    }
    
    public void setLo21Selected(short lo21Selected) {
        this.lo21Selected = lo21Selected;
    }
    public Short getLo21Exptime() {
        return this.lo21Exptime;
    }
    
    public void setLo21Exptime(Short lo21Exptime) {
        this.lo21Exptime = lo21Exptime;
    }
    public Short getLo21Numcycles() {
        return this.lo21Numcycles;
    }
    
    public void setLo21Numcycles(Short lo21Numcycles) {
        this.lo21Numcycles = lo21Numcycles;
    }
    public String getMode() {
        return this.mode;
    }
    
    public void setMode(String mode) {
        this.mode = mode;
    }
    public String getPeakupmode() {
        return this.peakupmode;
    }
    
    public void setPeakupmode(String peakupmode) {
        this.peakupmode = peakupmode;
    }
    public String getPeakupaccuracy() {
        return this.peakupaccuracy;
    }
    
    public void setPeakupaccuracy(String peakupaccuracy) {
        this.peakupaccuracy = peakupaccuracy;
    }
    public String getPeakupfilter() {
        return this.peakupfilter;
    }
    
    public void setPeakupfilter(String peakupfilter) {
        this.peakupfilter = peakupfilter;
    }
    public Float getPeakupfluxd() {
        return this.peakupfluxd;
    }
    
    public void setPeakupfluxd(Float peakupfluxd) {
        this.peakupfluxd = peakupfluxd;
    }
    public short getExtendpksource() {
        return this.extendpksource;
    }
    
    public void setExtendpksource(short extendpksource) {
        this.extendpksource = extendpksource;
    }
    public short getIspeakupposition() {
        return this.ispeakupposition;
    }
    
    public void setIspeakupposition(short ispeakupposition) {
        this.ispeakupposition = ispeakupposition;
    }
    public Float getOffsetraj2000() {
        return this.offsetraj2000;
    }
    
    public void setOffsetraj2000(Float offsetraj2000) {
        this.offsetraj2000 = offsetraj2000;
    }
    public Float getOffsetdecj2000() {
        return this.offsetdecj2000;
    }
    
    public void setOffsetdecj2000(Float offsetdecj2000) {
        this.offsetdecj2000 = offsetdecj2000;
    }
    public Double getPositionraj2000() {
        return this.positionraj2000;
    }
    
    public void setPositionraj2000(Double positionraj2000) {
        this.positionraj2000 = positionraj2000;
    }
    public Double getPositiondecj2000() {
        return this.positiondecj2000;
    }
    
    public void setPositiondecj2000(Double positiondecj2000) {
        this.positiondecj2000 = positiondecj2000;
    }
    public Float getPosrapmj2000() {
        return this.posrapmj2000;
    }
    
    public void setPosrapmj2000(Float posrapmj2000) {
        this.posrapmj2000 = posrapmj2000;
    }
    public Float getPosdecpmj2000() {
        return this.posdecpmj2000;
    }
    
    public void setPosdecpmj2000(Float posdecpmj2000) {
        this.posdecpmj2000 = posdecpmj2000;
    }
    public String getLat() {
        return this.lat;
    }
    
    public void setLat(String lat) {
        this.lat = lat;
    }
    public String getLon() {
        return this.lon;
    }
    
    public void setLon(String lon) {
        this.lon = lon;
    }
    public Float getEpoch() {
        return this.epoch;
    }
    
    public void setEpoch(Float epoch) {
        this.epoch = epoch;
    }
    public short getIsbackgroundaor() {
        return this.isbackgroundaor;
    }
    
    public void setIsbackgroundaor(short isbackgroundaor) {
        this.isbackgroundaor = isbackgroundaor;
    }




}


