package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * MipsPhot generated by hbm2java
 */
public class MipsPhot  implements java.io.Serializable {


     private int reqkey;
     private RequestInformation requestinformation;
     private short w160Selected;
     private Short w160Exptime;
     private short w160Fieldlarge;
     private short w160Enhanced;
     private Short w160Ncycles;
     private Float w160Refdelta;
     private short w24Selected;
     private Short w24Exptime;
     private short w24Fieldlarge;
     private Short w24Ncycles;
     private Float w24Refdelta;
     private short w70Selected;
     private Short w70Exptime;
     private short w70Fieldlarge;
     private Short w70Ncycles;
     private Float w70Refdelta;
     private short w70Scalefine;
     private short w24Rastermap;
     private Short w24Numcols;
     private Short w24Numrows;
     private String w24Colstepsize;
     private String w24Rowstepsize;
     private Short w24Mapcycles;
     private short w70Rastermap;
     private Short w70Numcols;
     private Short w70Numrows;
     private String w70Colstepsize;
     private String w70Rowstepsize;
     private Short w70Mapcycles;
     private short w160Rastermap;
     private Short w160Numcols;
     private Short w160Numrows;
     private String w160Colstepsize;
     private String w160Rowstepsize;
     private Short w160Mapcycles;

    public MipsPhot() {
    }

	
    public MipsPhot(int reqkey, RequestInformation requestinformation, short w160Selected, short w160Fieldlarge, short w160Enhanced, short w24Selected, short w24Fieldlarge, short w70Selected, short w70Fieldlarge, short w70Scalefine, short w24Rastermap, short w70Rastermap, short w160Rastermap) {
        this.reqkey = reqkey;
        this.requestinformation = requestinformation;
        this.w160Selected = w160Selected;
        this.w160Fieldlarge = w160Fieldlarge;
        this.w160Enhanced = w160Enhanced;
        this.w24Selected = w24Selected;
        this.w24Fieldlarge = w24Fieldlarge;
        this.w70Selected = w70Selected;
        this.w70Fieldlarge = w70Fieldlarge;
        this.w70Scalefine = w70Scalefine;
        this.w24Rastermap = w24Rastermap;
        this.w70Rastermap = w70Rastermap;
        this.w160Rastermap = w160Rastermap;
    }
    public MipsPhot(int reqkey, RequestInformation requestinformation, short w160Selected, Short w160Exptime, short w160Fieldlarge, short w160Enhanced, Short w160Ncycles, Float w160Refdelta, short w24Selected, Short w24Exptime, short w24Fieldlarge, Short w24Ncycles, Float w24Refdelta, short w70Selected, Short w70Exptime, short w70Fieldlarge, Short w70Ncycles, Float w70Refdelta, short w70Scalefine, short w24Rastermap, Short w24Numcols, Short w24Numrows, String w24Colstepsize, String w24Rowstepsize, Short w24Mapcycles, short w70Rastermap, Short w70Numcols, Short w70Numrows, String w70Colstepsize, String w70Rowstepsize, Short w70Mapcycles, short w160Rastermap, Short w160Numcols, Short w160Numrows, String w160Colstepsize, String w160Rowstepsize, Short w160Mapcycles) {
       this.reqkey = reqkey;
       this.requestinformation = requestinformation;
       this.w160Selected = w160Selected;
       this.w160Exptime = w160Exptime;
       this.w160Fieldlarge = w160Fieldlarge;
       this.w160Enhanced = w160Enhanced;
       this.w160Ncycles = w160Ncycles;
       this.w160Refdelta = w160Refdelta;
       this.w24Selected = w24Selected;
       this.w24Exptime = w24Exptime;
       this.w24Fieldlarge = w24Fieldlarge;
       this.w24Ncycles = w24Ncycles;
       this.w24Refdelta = w24Refdelta;
       this.w70Selected = w70Selected;
       this.w70Exptime = w70Exptime;
       this.w70Fieldlarge = w70Fieldlarge;
       this.w70Ncycles = w70Ncycles;
       this.w70Refdelta = w70Refdelta;
       this.w70Scalefine = w70Scalefine;
       this.w24Rastermap = w24Rastermap;
       this.w24Numcols = w24Numcols;
       this.w24Numrows = w24Numrows;
       this.w24Colstepsize = w24Colstepsize;
       this.w24Rowstepsize = w24Rowstepsize;
       this.w24Mapcycles = w24Mapcycles;
       this.w70Rastermap = w70Rastermap;
       this.w70Numcols = w70Numcols;
       this.w70Numrows = w70Numrows;
       this.w70Colstepsize = w70Colstepsize;
       this.w70Rowstepsize = w70Rowstepsize;
       this.w70Mapcycles = w70Mapcycles;
       this.w160Rastermap = w160Rastermap;
       this.w160Numcols = w160Numcols;
       this.w160Numrows = w160Numrows;
       this.w160Colstepsize = w160Colstepsize;
       this.w160Rowstepsize = w160Rowstepsize;
       this.w160Mapcycles = w160Mapcycles;
    }
   
    public int getReqkey() {
        return this.reqkey;
    }
    
    public void setReqkey(int reqkey) {
        this.reqkey = reqkey;
    }
    public RequestInformation getRequestinformation() {
        return this.requestinformation;
    }
    
    public void setRequestinformation(RequestInformation requestinformation) {
        this.requestinformation = requestinformation;
    }
    public short getW160Selected() {
        return this.w160Selected;
    }
    
    public void setW160Selected(short w160Selected) {
        this.w160Selected = w160Selected;
    }
    public Short getW160Exptime() {
        return this.w160Exptime;
    }
    
    public void setW160Exptime(Short w160Exptime) {
        this.w160Exptime = w160Exptime;
    }
    public short getW160Fieldlarge() {
        return this.w160Fieldlarge;
    }
    
    public void setW160Fieldlarge(short w160Fieldlarge) {
        this.w160Fieldlarge = w160Fieldlarge;
    }
    public short getW160Enhanced() {
        return this.w160Enhanced;
    }
    
    public void setW160Enhanced(short w160Enhanced) {
        this.w160Enhanced = w160Enhanced;
    }
    public Short getW160Ncycles() {
        return this.w160Ncycles;
    }
    
    public void setW160Ncycles(Short w160Ncycles) {
        this.w160Ncycles = w160Ncycles;
    }
    public Float getW160Refdelta() {
        return this.w160Refdelta;
    }
    
    public void setW160Refdelta(Float w160Refdelta) {
        this.w160Refdelta = w160Refdelta;
    }
    public short getW24Selected() {
        return this.w24Selected;
    }
    
    public void setW24Selected(short w24Selected) {
        this.w24Selected = w24Selected;
    }
    public Short getW24Exptime() {
        return this.w24Exptime;
    }
    
    public void setW24Exptime(Short w24Exptime) {
        this.w24Exptime = w24Exptime;
    }
    public short getW24Fieldlarge() {
        return this.w24Fieldlarge;
    }
    
    public void setW24Fieldlarge(short w24Fieldlarge) {
        this.w24Fieldlarge = w24Fieldlarge;
    }
    public Short getW24Ncycles() {
        return this.w24Ncycles;
    }
    
    public void setW24Ncycles(Short w24Ncycles) {
        this.w24Ncycles = w24Ncycles;
    }
    public Float getW24Refdelta() {
        return this.w24Refdelta;
    }
    
    public void setW24Refdelta(Float w24Refdelta) {
        this.w24Refdelta = w24Refdelta;
    }
    public short getW70Selected() {
        return this.w70Selected;
    }
    
    public void setW70Selected(short w70Selected) {
        this.w70Selected = w70Selected;
    }
    public Short getW70Exptime() {
        return this.w70Exptime;
    }
    
    public void setW70Exptime(Short w70Exptime) {
        this.w70Exptime = w70Exptime;
    }
    public short getW70Fieldlarge() {
        return this.w70Fieldlarge;
    }
    
    public void setW70Fieldlarge(short w70Fieldlarge) {
        this.w70Fieldlarge = w70Fieldlarge;
    }
    public Short getW70Ncycles() {
        return this.w70Ncycles;
    }
    
    public void setW70Ncycles(Short w70Ncycles) {
        this.w70Ncycles = w70Ncycles;
    }
    public Float getW70Refdelta() {
        return this.w70Refdelta;
    }
    
    public void setW70Refdelta(Float w70Refdelta) {
        this.w70Refdelta = w70Refdelta;
    }
    public short getW70Scalefine() {
        return this.w70Scalefine;
    }
    
    public void setW70Scalefine(short w70Scalefine) {
        this.w70Scalefine = w70Scalefine;
    }
    public short getW24Rastermap() {
        return this.w24Rastermap;
    }
    
    public void setW24Rastermap(short w24Rastermap) {
        this.w24Rastermap = w24Rastermap;
    }
    public Short getW24Numcols() {
        return this.w24Numcols;
    }
    
    public void setW24Numcols(Short w24Numcols) {
        this.w24Numcols = w24Numcols;
    }
    public Short getW24Numrows() {
        return this.w24Numrows;
    }
    
    public void setW24Numrows(Short w24Numrows) {
        this.w24Numrows = w24Numrows;
    }
    public String getW24Colstepsize() {
        return this.w24Colstepsize;
    }
    
    public void setW24Colstepsize(String w24Colstepsize) {
        this.w24Colstepsize = w24Colstepsize;
    }
    public String getW24Rowstepsize() {
        return this.w24Rowstepsize;
    }
    
    public void setW24Rowstepsize(String w24Rowstepsize) {
        this.w24Rowstepsize = w24Rowstepsize;
    }
    public Short getW24Mapcycles() {
        return this.w24Mapcycles;
    }
    
    public void setW24Mapcycles(Short w24Mapcycles) {
        this.w24Mapcycles = w24Mapcycles;
    }
    public short getW70Rastermap() {
        return this.w70Rastermap;
    }
    
    public void setW70Rastermap(short w70Rastermap) {
        this.w70Rastermap = w70Rastermap;
    }
    public Short getW70Numcols() {
        return this.w70Numcols;
    }
    
    public void setW70Numcols(Short w70Numcols) {
        this.w70Numcols = w70Numcols;
    }
    public Short getW70Numrows() {
        return this.w70Numrows;
    }
    
    public void setW70Numrows(Short w70Numrows) {
        this.w70Numrows = w70Numrows;
    }
    public String getW70Colstepsize() {
        return this.w70Colstepsize;
    }
    
    public void setW70Colstepsize(String w70Colstepsize) {
        this.w70Colstepsize = w70Colstepsize;
    }
    public String getW70Rowstepsize() {
        return this.w70Rowstepsize;
    }
    
    public void setW70Rowstepsize(String w70Rowstepsize) {
        this.w70Rowstepsize = w70Rowstepsize;
    }
    public Short getW70Mapcycles() {
        return this.w70Mapcycles;
    }
    
    public void setW70Mapcycles(Short w70Mapcycles) {
        this.w70Mapcycles = w70Mapcycles;
    }
    public short getW160Rastermap() {
        return this.w160Rastermap;
    }
    
    public void setW160Rastermap(short w160Rastermap) {
        this.w160Rastermap = w160Rastermap;
    }
    public Short getW160Numcols() {
        return this.w160Numcols;
    }
    
    public void setW160Numcols(Short w160Numcols) {
        this.w160Numcols = w160Numcols;
    }
    public Short getW160Numrows() {
        return this.w160Numrows;
    }
    
    public void setW160Numrows(Short w160Numrows) {
        this.w160Numrows = w160Numrows;
    }
    public String getW160Colstepsize() {
        return this.w160Colstepsize;
    }
    
    public void setW160Colstepsize(String w160Colstepsize) {
        this.w160Colstepsize = w160Colstepsize;
    }
    public String getW160Rowstepsize() {
        return this.w160Rowstepsize;
    }
    
    public void setW160Rowstepsize(String w160Rowstepsize) {
        this.w160Rowstepsize = w160Rowstepsize;
    }
    public Short getW160Mapcycles() {
        return this.w160Mapcycles;
    }
    
    public void setW160Mapcycles(Short w160Mapcycles) {
        this.w160Mapcycles = w160Mapcycles;
    }




}


