package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * MipsTP generated by hbm2java
 */
public class MipsTP  implements java.io.Serializable {


     private int reqkey;
     private RequestInformation requestinformation;
     private short w24Selected;
     private Short w24Exptime;
     private Short w24Ncycles;
     private short w70Selected;
     private Short w70Exptime;
     private Short w70Ncycles;
     private short w160Selected;
     private Short w160Exptime;
     private Short w160Ncycles;

    public MipsTP() {
    }

	
    public MipsTP(int reqkey, RequestInformation requestinformation, short w24Selected, short w70Selected, short w160Selected) {
        this.reqkey = reqkey;
        this.requestinformation = requestinformation;
        this.w24Selected = w24Selected;
        this.w70Selected = w70Selected;
        this.w160Selected = w160Selected;
    }
    public MipsTP(int reqkey, RequestInformation requestinformation, short w24Selected, Short w24Exptime, Short w24Ncycles, short w70Selected, Short w70Exptime, Short w70Ncycles, short w160Selected, Short w160Exptime, Short w160Ncycles) {
       this.reqkey = reqkey;
       this.requestinformation = requestinformation;
       this.w24Selected = w24Selected;
       this.w24Exptime = w24Exptime;
       this.w24Ncycles = w24Ncycles;
       this.w70Selected = w70Selected;
       this.w70Exptime = w70Exptime;
       this.w70Ncycles = w70Ncycles;
       this.w160Selected = w160Selected;
       this.w160Exptime = w160Exptime;
       this.w160Ncycles = w160Ncycles;
    }
   
    public int getReqkey() {
        return this.reqkey;
    }
    
    public void setReqkey(int reqkey) {
        this.reqkey = reqkey;
    }
    public RequestInformation getRequestinformation() {
        return this.requestinformation;
    }
    
    public void setRequestinformation(RequestInformation requestinformation) {
        this.requestinformation = requestinformation;
    }
    public short getW24Selected() {
        return this.w24Selected;
    }
    
    public void setW24Selected(short w24Selected) {
        this.w24Selected = w24Selected;
    }
    public Short getW24Exptime() {
        return this.w24Exptime;
    }
    
    public void setW24Exptime(Short w24Exptime) {
        this.w24Exptime = w24Exptime;
    }
    public Short getW24Ncycles() {
        return this.w24Ncycles;
    }
    
    public void setW24Ncycles(Short w24Ncycles) {
        this.w24Ncycles = w24Ncycles;
    }
    public short getW70Selected() {
        return this.w70Selected;
    }
    
    public void setW70Selected(short w70Selected) {
        this.w70Selected = w70Selected;
    }
    public Short getW70Exptime() {
        return this.w70Exptime;
    }
    
    public void setW70Exptime(Short w70Exptime) {
        this.w70Exptime = w70Exptime;
    }
    public Short getW70Ncycles() {
        return this.w70Ncycles;
    }
    
    public void setW70Ncycles(Short w70Ncycles) {
        this.w70Ncycles = w70Ncycles;
    }
    public short getW160Selected() {
        return this.w160Selected;
    }
    
    public void setW160Selected(short w160Selected) {
        this.w160Selected = w160Selected;
    }
    public Short getW160Exptime() {
        return this.w160Exptime;
    }
    
    public void setW160Exptime(Short w160Exptime) {
        this.w160Exptime = w160Exptime;
    }
    public Short getW160Ncycles() {
        return this.w160Ncycles;
    }
    
    public void setW160Ncycles(Short w160Ncycles) {
        this.w160Ncycles = w160Ncycles;
    }




}


