package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * MipsScan generated by hbm2java
 */
public class MipsScan  implements java.io.Serializable {


     private int reqkey;
     private RequestInformation requestinformation;
     private Short crossscanoffset;
     private short fastreset160;
     private Short inscanoffset;
     private Short nmapcycles;
     private Short nscanlegs;
     private short require160;
     private Float scanleglength;
     private String scanrate;
     private Short stepsizefwd;
     private Short stepsizerev;
     private short backwardmap;

    public MipsScan() {
    }

	
    public MipsScan(int reqkey, RequestInformation requestinformation, short fastreset160, short require160, short backwardmap) {
        this.reqkey = reqkey;
        this.requestinformation = requestinformation;
        this.fastreset160 = fastreset160;
        this.require160 = require160;
        this.backwardmap = backwardmap;
    }
    public MipsScan(int reqkey, RequestInformation requestinformation, Short crossscanoffset, short fastreset160, Short inscanoffset, Short nmapcycles, Short nscanlegs, short require160, Float scanleglength, String scanrate, Short stepsizefwd, Short stepsizerev, short backwardmap) {
       this.reqkey = reqkey;
       this.requestinformation = requestinformation;
       this.crossscanoffset = crossscanoffset;
       this.fastreset160 = fastreset160;
       this.inscanoffset = inscanoffset;
       this.nmapcycles = nmapcycles;
       this.nscanlegs = nscanlegs;
       this.require160 = require160;
       this.scanleglength = scanleglength;
       this.scanrate = scanrate;
       this.stepsizefwd = stepsizefwd;
       this.stepsizerev = stepsizerev;
       this.backwardmap = backwardmap;
    }
   
    public int getReqkey() {
        return this.reqkey;
    }
    
    public void setReqkey(int reqkey) {
        this.reqkey = reqkey;
    }
    public RequestInformation getRequestinformation() {
        return this.requestinformation;
    }
    
    public void setRequestinformation(RequestInformation requestinformation) {
        this.requestinformation = requestinformation;
    }
    public Short getCrossscanoffset() {
        return this.crossscanoffset;
    }
    
    public void setCrossscanoffset(Short crossscanoffset) {
        this.crossscanoffset = crossscanoffset;
    }
    public short getFastreset160() {
        return this.fastreset160;
    }
    
    public void setFastreset160(short fastreset160) {
        this.fastreset160 = fastreset160;
    }
    public Short getInscanoffset() {
        return this.inscanoffset;
    }
    
    public void setInscanoffset(Short inscanoffset) {
        this.inscanoffset = inscanoffset;
    }
    public Short getNmapcycles() {
        return this.nmapcycles;
    }
    
    public void setNmapcycles(Short nmapcycles) {
        this.nmapcycles = nmapcycles;
    }
    public Short getNscanlegs() {
        return this.nscanlegs;
    }
    
    public void setNscanlegs(Short nscanlegs) {
        this.nscanlegs = nscanlegs;
    }
    public short getRequire160() {
        return this.require160;
    }
    
    public void setRequire160(short require160) {
        this.require160 = require160;
    }
    public Float getScanleglength() {
        return this.scanleglength;
    }
    
    public void setScanleglength(Float scanleglength) {
        this.scanleglength = scanleglength;
    }
    public String getScanrate() {
        return this.scanrate;
    }
    
    public void setScanrate(String scanrate) {
        this.scanrate = scanrate;
    }
    public Short getStepsizefwd() {
        return this.stepsizefwd;
    }
    
    public void setStepsizefwd(Short stepsizefwd) {
        this.stepsizefwd = stepsizefwd;
    }
    public Short getStepsizerev() {
        return this.stepsizerev;
    }
    
    public void setStepsizerev(Short stepsizerev) {
        this.stepsizerev = stepsizerev;
    }
    public short getBackwardmap() {
        return this.backwardmap;
    }
    
    public void setBackwardmap(short backwardmap) {
        this.backwardmap = backwardmap;
    }




}


