package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * MipsSed generated by hbm2java
 */
public class MipsSed  implements java.io.Serializable {


     private int reqkey;
     private RequestInformation requestinformation;
     private String chopdist;
     private Short exptime;
     private Boolean rastermap;
     private Short numcols;
     private Short numrows;
     private String colstepsize;
     private String rowstepsize;
     private Short mapcycles;
     private Short ncycles;

    public MipsSed() {
    }

	
    public MipsSed(int reqkey, RequestInformation requestinformation) {
        this.reqkey = reqkey;
        this.requestinformation = requestinformation;
    }
    public MipsSed(int reqkey, RequestInformation requestinformation, String chopdist, Short exptime, Boolean rastermap, Short numcols, Short numrows, String colstepsize, String rowstepsize, Short mapcycles, Short ncycles) {
       this.reqkey = reqkey;
       this.requestinformation = requestinformation;
       this.chopdist = chopdist;
       this.exptime = exptime;
       this.rastermap = rastermap;
       this.numcols = numcols;
       this.numrows = numrows;
       this.colstepsize = colstepsize;
       this.rowstepsize = rowstepsize;
       this.mapcycles = mapcycles;
       this.ncycles = ncycles;
    }
   
    public int getReqkey() {
        return this.reqkey;
    }
    
    public void setReqkey(int reqkey) {
        this.reqkey = reqkey;
    }
    public RequestInformation getRequestinformation() {
        return this.requestinformation;
    }
    
    public void setRequestinformation(RequestInformation requestinformation) {
        this.requestinformation = requestinformation;
    }
    public String getChopdist() {
        return this.chopdist;
    }
    
    public void setChopdist(String chopdist) {
        this.chopdist = chopdist;
    }
    public Short getExptime() {
        return this.exptime;
    }
    
    public void setExptime(Short exptime) {
        this.exptime = exptime;
    }
    public Boolean getRastermap() {
        return this.rastermap;
    }
    
    public void setRastermap(Boolean rastermap) {
        this.rastermap = rastermap;
    }
    public Short getNumcols() {
        return this.numcols;
    }
    
    public void setNumcols(Short numcols) {
        this.numcols = numcols;
    }
    public Short getNumrows() {
        return this.numrows;
    }
    
    public void setNumrows(Short numrows) {
        this.numrows = numrows;
    }
    public String getColstepsize() {
        return this.colstepsize;
    }
    
    public void setColstepsize(String colstepsize) {
        this.colstepsize = colstepsize;
    }
    public String getRowstepsize() {
        return this.rowstepsize;
    }
    
    public void setRowstepsize(String rowstepsize) {
        this.rowstepsize = rowstepsize;
    }
    public Short getMapcycles() {
        return this.mapcycles;
    }
    
    public void setMapcycles(Short mapcycles) {
        this.mapcycles = mapcycles;
    }
    public Short getNcycles() {
        return this.ncycles;
    }
    
    public void setNcycles(Short ncycles) {
        this.ncycles = ncycles;
    }




}


