package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PointingFiles generated by hbm2java
 */
public class PointingFiles  implements java.io.Serializable {


     private int ptgfileid;
     private int ptgftid;
     private String filename;
     private long filesize;
     private String checksum;
     private int startsclk;
     private int endsclk;
     private Date startscet;
     private Date endscet;

    public PointingFiles() {
    }

	
    public PointingFiles(int ptgfileid, int ptgftid, String filename, long filesize, int startsclk, int endsclk, Date startscet, Date endscet) {
        this.ptgfileid = ptgfileid;
        this.ptgftid = ptgftid;
        this.filename = filename;
        this.filesize = filesize;
        this.startsclk = startsclk;
        this.endsclk = endsclk;
        this.startscet = startscet;
        this.endscet = endscet;
    }
    public PointingFiles(int ptgfileid, int ptgftid, String filename, long filesize, String checksum, int startsclk, int endsclk, Date startscet, Date endscet) {
       this.ptgfileid = ptgfileid;
       this.ptgftid = ptgftid;
       this.filename = filename;
       this.filesize = filesize;
       this.checksum = checksum;
       this.startsclk = startsclk;
       this.endsclk = endsclk;
       this.startscet = startscet;
       this.endscet = endscet;
    }
   
    public int getPtgfileid() {
        return this.ptgfileid;
    }
    
    public void setPtgfileid(int ptgfileid) {
        this.ptgfileid = ptgfileid;
    }
    public int getPtgftid() {
        return this.ptgftid;
    }
    
    public void setPtgftid(int ptgftid) {
        this.ptgftid = ptgftid;
    }
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }
    public long getFilesize() {
        return this.filesize;
    }
    
    public void setFilesize(long filesize) {
        this.filesize = filesize;
    }
    public String getChecksum() {
        return this.checksum;
    }
    
    public void setChecksum(String checksum) {
        this.checksum = checksum;
    }
    public int getStartsclk() {
        return this.startsclk;
    }
    
    public void setStartsclk(int startsclk) {
        this.startsclk = startsclk;
    }
    public int getEndsclk() {
        return this.endsclk;
    }
    
    public void setEndsclk(int endsclk) {
        this.endsclk = endsclk;
    }
    public Date getStartscet() {
        return this.startscet;
    }
    
    public void setStartscet(Date startscet) {
        this.startscet = startscet;
    }
    public Date getEndscet() {
        return this.endscet;
    }
    
    public void setEndscet(Date endscet) {
        this.endscet = endscet;
    }




}


