package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * PostbcdProducts generated by hbm2java
 */
public class PostbcdProducts  implements java.io.Serializable {


     private int pbcdid;
     private CampaignInformation campaigninformation;
     private RequestInformation requestinformation;
     private int ensid;
     private short channum;
     private short plscriptid;
     private Integer dcesetid;
     private short ruleid;
     private short ensofens;
     private Short actualinputs;
     private String heritagefilename;
     private Integer ptid;
     private String ptcomment;
     private int filesize;
     private String checksum;
     private String reqmode;
     private double ra;
     private double dec;
     private W3Info w3info;
     private String archivefilename;

    public PostbcdProducts() {
    }

	
    public PostbcdProducts(int pbcdid, CampaignInformation campaigninformation, RequestInformation requestinformation, int ensid, short channum, short plscriptid, short ruleid, short ensofens, int filesize, String checksum, String reqmode, double ra, double dec, W3Info w3info) {
        this.pbcdid = pbcdid;
        this.campaigninformation = campaigninformation;
        this.requestinformation = requestinformation;
        this.ensid = ensid;
        this.channum = channum;
        this.plscriptid = plscriptid;
        this.ruleid = ruleid;
        this.ensofens = ensofens;
        this.filesize = filesize;
        this.checksum = checksum;
        this.reqmode = reqmode;
        this.ra = ra;
        this.dec = dec;
        this.w3info = w3info;
    }
    public PostbcdProducts(int pbcdid, CampaignInformation campaigninformation, RequestInformation requestinformation, int ensid, short channum, short plscriptid, Integer dcesetid, short ruleid, short ensofens, Short actualinputs, String heritagefilename, Integer ptid, String ptcomment, int filesize, String checksum, String reqmode, double ra, double dec, W3Info w3info, String archivefilename) {
       this.pbcdid = pbcdid;
       this.campaigninformation = campaigninformation;
       this.requestinformation = requestinformation;
       this.ensid = ensid;
       this.channum = channum;
       this.plscriptid = plscriptid;
       this.dcesetid = dcesetid;
       this.ruleid = ruleid;
       this.ensofens = ensofens;
       this.actualinputs = actualinputs;
       this.heritagefilename = heritagefilename;
       this.ptid = ptid;
       this.ptcomment = ptcomment;
       this.filesize = filesize;
       this.checksum = checksum;
       this.reqmode = reqmode;
       this.ra = ra;
       this.dec = dec;
       this.w3info = w3info;
       this.archivefilename = archivefilename;
    }
   
    public int getPbcdid() {
        return this.pbcdid;
    }
    
    public void setPbcdid(int pbcdid) {
        this.pbcdid = pbcdid;
    }
    public CampaignInformation getCampaigninformation() {
        return this.campaigninformation;
    }
    
    public void setCampaigninformation(CampaignInformation campaigninformation) {
        this.campaigninformation = campaigninformation;
    }
    public RequestInformation getRequestinformation() {
        return this.requestinformation;
    }
    
    public void setRequestinformation(RequestInformation requestinformation) {
        this.requestinformation = requestinformation;
    }
    public int getEnsid() {
        return this.ensid;
    }
    
    public void setEnsid(int ensid) {
        this.ensid = ensid;
    }
    public short getChannum() {
        return this.channum;
    }
    
    public void setChannum(short channum) {
        this.channum = channum;
    }
    public short getPlscriptid() {
        return this.plscriptid;
    }
    
    public void setPlscriptid(short plscriptid) {
        this.plscriptid = plscriptid;
    }
    public Integer getDcesetid() {
        return this.dcesetid;
    }
    
    public void setDcesetid(Integer dcesetid) {
        this.dcesetid = dcesetid;
    }
    public short getRuleid() {
        return this.ruleid;
    }
    
    public void setRuleid(short ruleid) {
        this.ruleid = ruleid;
    }
    public short getEnsofens() {
        return this.ensofens;
    }
    
    public void setEnsofens(short ensofens) {
        this.ensofens = ensofens;
    }
    public Short getActualinputs() {
        return this.actualinputs;
    }
    
    public void setActualinputs(Short actualinputs) {
        this.actualinputs = actualinputs;
    }
    public String getHeritagefilename() {
        return this.heritagefilename;
    }
    
    public void setHeritagefilename(String heritagefilename) {
        this.heritagefilename = heritagefilename;
    }
    public Integer getPtid() {
        return this.ptid;
    }
    
    public void setPtid(Integer ptid) {
        this.ptid = ptid;
    }
    public String getPtcomment() {
        return this.ptcomment;
    }
    
    public void setPtcomment(String ptcomment) {
        this.ptcomment = ptcomment;
    }
    public int getFilesize() {
        return this.filesize;
    }
    
    public void setFilesize(int filesize) {
        this.filesize = filesize;
    }
    public String getChecksum() {
        return this.checksum;
    }
    
    public void setChecksum(String checksum) {
        this.checksum = checksum;
    }
    public String getReqmode() {
        return this.reqmode;
    }
    
    public void setReqmode(String reqmode) {
        this.reqmode = reqmode;
    }
    public double getRa() {
        return this.ra;
    }
    
    public void setRa(double ra) {
        this.ra = ra;
    }
    public double getDec() {
        return this.dec;
    }
    
    public void setDec(double dec) {
        this.dec = dec;
    }
    public W3Info getW3info() {
        return this.w3info;
    }
    
    public void setW3info(W3Info w3info) {
        this.w3info = w3info;
    }
    public String getArchivefilename() {
        return this.archivefilename;
    }
    
    public void setArchivefilename(String archivefilename) {
        this.archivefilename = archivefilename;
    }




}


