package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * PostbcdAncilProducts generated by hbm2java
 */
public class PostbcdAncilProducts  implements java.io.Serializable {


     private int ancilid;
     private PostbcdProducts postbcdproducts;
     private CampaignInformation campaigninformation;
     private String heritagefilename;
     private String fileextension;
     private String type;
     private Integer ptid;
     private String ptcomment;
     private int filesize;
     private String checksum;
     private String archivefilename;

    public PostbcdAncilProducts() {
    }

	
    public PostbcdAncilProducts(int ancilid, PostbcdProducts postbcdproducts, CampaignInformation campaigninformation, int filesize, String checksum) {
        this.ancilid = ancilid;
        this.postbcdproducts = postbcdproducts;
        this.campaigninformation = campaigninformation;
        this.filesize = filesize;
        this.checksum = checksum;
    }
    public PostbcdAncilProducts(int ancilid, PostbcdProducts postbcdproducts, CampaignInformation campaigninformation, String heritagefilename, String fileextension, String type, Integer ptid, String ptcomment, int filesize, String checksum, String archivefilename) {
       this.ancilid = ancilid;
       this.postbcdproducts = postbcdproducts;
       this.campaigninformation = campaigninformation;
       this.heritagefilename = heritagefilename;
       this.fileextension = fileextension;
       this.type = type;
       this.ptid = ptid;
       this.ptcomment = ptcomment;
       this.filesize = filesize;
       this.checksum = checksum;
       this.archivefilename = archivefilename;
    }
   
    public int getAncilid() {
        return this.ancilid;
    }
    
    public void setAncilid(int ancilid) {
        this.ancilid = ancilid;
    }
    public PostbcdProducts getPostbcdproducts() {
        return this.postbcdproducts;
    }
    
    public void setPostbcdproducts(PostbcdProducts postbcdproducts) {
        this.postbcdproducts = postbcdproducts;
    }
    public CampaignInformation getCampaigninformation() {
        return this.campaigninformation;
    }
    
    public void setCampaigninformation(CampaignInformation campaigninformation) {
        this.campaigninformation = campaigninformation;
    }
    public String getHeritagefilename() {
        return this.heritagefilename;
    }
    
    public void setHeritagefilename(String heritagefilename) {
        this.heritagefilename = heritagefilename;
    }
    public String getFileextension() {
        return this.fileextension;
    }
    
    public void setFileextension(String fileextension) {
        this.fileextension = fileextension;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Integer getPtid() {
        return this.ptid;
    }
    
    public void setPtid(Integer ptid) {
        this.ptid = ptid;
    }
    public String getPtcomment() {
        return this.ptcomment;
    }
    
    public void setPtcomment(String ptcomment) {
        this.ptcomment = ptcomment;
    }
    public int getFilesize() {
        return this.filesize;
    }
    
    public void setFilesize(int filesize) {
        this.filesize = filesize;
    }
    public String getChecksum() {
        return this.checksum;
    }
    
    public void setChecksum(String checksum) {
        this.checksum = checksum;
    }
    public String getArchivefilename() {
        return this.archivefilename;
    }
    
    public void setArchivefilename(String archivefilename) {
        this.archivefilename = archivefilename;
    }




}


