package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * RequestInformation generated by hbm2java
 */
public class RequestInformation  implements java.io.Serializable {


     private int reqkey;
     private int campid;
     private int progid;
     private String progtitle;
     private String progname;
     private String progcat;
     private String sciencecat;
     private String pi;
     private String contact;
     private String abstract_;
     private String progobscomment;
     private String progcomment;
     private short latestversion;
     private String reqtitle;
     private String reqtype;
     private String reqmode;
     private String reqstatus;
     private Float boundingradius;
     private short brightobject;
     private String reqobscomment;
     private Date reqbegintime;
     private Date reqendtime;
     private String aorid;
     private short secondlook;
     private String qacomments;
     private String qareadmefile;
     private TargetInformation targetinformation;

    public RequestInformation() {
    }

	
    public RequestInformation(int reqkey, int campid, int progid, String progname, short latestversion, String reqtitle, String reqtype, String reqmode, String reqstatus, short brightobject, short secondlook, TargetInformation targetinformation) {
        this.reqkey = reqkey;
        this.campid = campid;
        this.progid = progid;
        this.progname = progname;
        this.latestversion = latestversion;
        this.reqtitle = reqtitle;
        this.reqtype = reqtype;
        this.reqmode = reqmode;
        this.reqstatus = reqstatus;
        this.brightobject = brightobject;
        this.secondlook = secondlook;
        this.targetinformation = targetinformation;
    }
    public RequestInformation(int reqkey, int campid, int progid, String progtitle, String progname, String progcat, String sciencecat, String pi, String contact, String abstract_, String progobscomment, String progcomment, short latestversion, String reqtitle, String reqtype, String reqmode, String reqstatus, Float boundingradius, short brightobject, String reqobscomment, Date reqbegintime, Date reqendtime, String aorid, short secondlook, String qacomments, String qareadmefile, TargetInformation targetinformation) {
       this.reqkey = reqkey;
       this.campid = campid;
       this.progid = progid;
       this.progtitle = progtitle;
       this.progname = progname;
       this.progcat = progcat;
       this.sciencecat = sciencecat;
       this.pi = pi;
       this.contact = contact;
       this.abstract_ = abstract_;
       this.progobscomment = progobscomment;
       this.progcomment = progcomment;
       this.latestversion = latestversion;
       this.reqtitle = reqtitle;
       this.reqtype = reqtype;
       this.reqmode = reqmode;
       this.reqstatus = reqstatus;
       this.boundingradius = boundingradius;
       this.brightobject = brightobject;
       this.reqobscomment = reqobscomment;
       this.reqbegintime = reqbegintime;
       this.reqendtime = reqendtime;
       this.aorid = aorid;
       this.secondlook = secondlook;
       this.qacomments = qacomments;
       this.qareadmefile = qareadmefile;
       this.targetinformation = targetinformation;
    }
   
    public int getReqkey() {
        return this.reqkey;
    }
    
    public void setReqkey(int reqkey) {
        this.reqkey = reqkey;
    }
    public int getCampid() {
        return this.campid;
    }
    
    public void setCampid(int campid) {
        this.campid = campid;
    }
    public int getProgid() {
        return this.progid;
    }
    
    public void setProgid(int progid) {
        this.progid = progid;
    }
    public String getProgtitle() {
        return this.progtitle;
    }
    
    public void setProgtitle(String progtitle) {
        this.progtitle = progtitle;
    }
    public String getProgname() {
        return this.progname;
    }
    
    public void setProgname(String progname) {
        this.progname = progname;
    }
    public String getProgcat() {
        return this.progcat;
    }
    
    public void setProgcat(String progcat) {
        this.progcat = progcat;
    }
    public String getSciencecat() {
        return this.sciencecat;
    }
    
    public void setSciencecat(String sciencecat) {
        this.sciencecat = sciencecat;
    }
    public String getPi() {
        return this.pi;
    }
    
    public void setPi(String pi) {
        this.pi = pi;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getAbstract_() {
        return this.abstract_;
    }
    
    public void setAbstract_(String abstract_) {
        this.abstract_ = abstract_;
    }
    public String getProgobscomment() {
        return this.progobscomment;
    }
    
    public void setProgobscomment(String progobscomment) {
        this.progobscomment = progobscomment;
    }
    public String getProgcomment() {
        return this.progcomment;
    }
    
    public void setProgcomment(String progcomment) {
        this.progcomment = progcomment;
    }
    public short getLatestversion() {
        return this.latestversion;
    }
    
    public void setLatestversion(short latestversion) {
        this.latestversion = latestversion;
    }
    public String getReqtitle() {
        return this.reqtitle;
    }
    
    public void setReqtitle(String reqtitle) {
        this.reqtitle = reqtitle;
    }
    public String getReqtype() {
        return this.reqtype;
    }
    
    public void setReqtype(String reqtype) {
        this.reqtype = reqtype;
    }
    public String getReqmode() {
        return this.reqmode;
    }
    
    public void setReqmode(String reqmode) {
        this.reqmode = reqmode;
    }
    public String getReqstatus() {
        return this.reqstatus;
    }
    
    public void setReqstatus(String reqstatus) {
        this.reqstatus = reqstatus;
    }
    public Float getBoundingradius() {
        return this.boundingradius;
    }
    
    public void setBoundingradius(Float boundingradius) {
        this.boundingradius = boundingradius;
    }
    public short getBrightobject() {
        return this.brightobject;
    }
    
    public void setBrightobject(short brightobject) {
        this.brightobject = brightobject;
    }
    public String getReqobscomment() {
        return this.reqobscomment;
    }
    
    public void setReqobscomment(String reqobscomment) {
        this.reqobscomment = reqobscomment;
    }
    public Date getReqbegintime() {
        return this.reqbegintime;
    }
    
    public void setReqbegintime(Date reqbegintime) {
        this.reqbegintime = reqbegintime;
    }
    public Date getReqendtime() {
        return this.reqendtime;
    }
    
    public void setReqendtime(Date reqendtime) {
        this.reqendtime = reqendtime;
    }
    public String getAorid() {
        return this.aorid;
    }
    
    public void setAorid(String aorid) {
        this.aorid = aorid;
    }
    public short getSecondlook() {
        return this.secondlook;
    }
    
    public void setSecondlook(short secondlook) {
        this.secondlook = secondlook;
    }
    public String getQacomments() {
        return this.qacomments;
    }
    
    public void setQacomments(String qacomments) {
        this.qacomments = qacomments;
    }
    public String getQareadmefile() {
        return this.qareadmefile;
    }
    
    public void setQareadmefile(String qareadmefile) {
        this.qareadmefile = qareadmefile;
    }
    public TargetInformation getTargetinformation() {
        return this.targetinformation;
    }
    
    public void setTargetinformation(TargetInformation targetinformation) {
        this.targetinformation = targetinformation;
    }




}


