package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * TargetInformation generated by hbm2java
 */
public class TargetInformation  implements java.io.Serializable {


     private int reqkey;
     private String targetname;
     private String targettype;
     private short avoidearth;
     private short avoidotherbo;
     private Integer label;
     private String coordsys;
     private Double decj2000;
     private Float decpmj2000;
     private Integer doy;
     private Float epoch;
     private String equinox;
     private String lat;
     private String latpm;
     private String lon;
     private String lonpm;
     private Double raj2000;
     private Float rapmj2000;
     private String tgtposlist;
     private short arraycoord;
     private short onlyoffsets;
     private String offsets;
     private Integer naifid;
     private String naifname;

    public TargetInformation() {
    }

	
    public TargetInformation(int reqkey, short avoidearth, short avoidotherbo, short arraycoord, short onlyoffsets) {
        this.reqkey = reqkey;
        this.avoidearth = avoidearth;
        this.avoidotherbo = avoidotherbo;
        this.arraycoord = arraycoord;
        this.onlyoffsets = onlyoffsets;
    }
    public TargetInformation(int reqkey, String targetname, String targettype, short avoidearth, short avoidotherbo, Integer label, String coordsys, Double decj2000, Float decpmj2000, Integer doy, Float epoch, String equinox, String lat, String latpm, String lon, String lonpm, Double raj2000, Float rapmj2000, String tgtposlist, short arraycoord, short onlyoffsets, String offsets, Integer naifid, String naifname) {
       this.reqkey = reqkey;
       this.targetname = targetname;
       this.targettype = targettype;
       this.avoidearth = avoidearth;
       this.avoidotherbo = avoidotherbo;
       this.label = label;
       this.coordsys = coordsys;
       this.decj2000 = decj2000;
       this.decpmj2000 = decpmj2000;
       this.doy = doy;
       this.epoch = epoch;
       this.equinox = equinox;
       this.lat = lat;
       this.latpm = latpm;
       this.lon = lon;
       this.lonpm = lonpm;
       this.raj2000 = raj2000;
       this.rapmj2000 = rapmj2000;
       this.tgtposlist = tgtposlist;
       this.arraycoord = arraycoord;
       this.onlyoffsets = onlyoffsets;
       this.offsets = offsets;
       this.naifid = naifid;
       this.naifname = naifname;
    }
   
    public int getReqkey() {
        return this.reqkey;
    }
    
    public void setReqkey(int reqkey) {
        this.reqkey = reqkey;
    }
    public String getTargetname() {
        return this.targetname;
    }
    
    public void setTargetname(String targetname) {
        this.targetname = targetname;
    }
    public String getTargettype() {
        return this.targettype;
    }
    
    public void setTargettype(String targettype) {
        this.targettype = targettype;
    }
    public short getAvoidearth() {
        return this.avoidearth;
    }
    
    public void setAvoidearth(short avoidearth) {
        this.avoidearth = avoidearth;
    }
    public short getAvoidotherbo() {
        return this.avoidotherbo;
    }
    
    public void setAvoidotherbo(short avoidotherbo) {
        this.avoidotherbo = avoidotherbo;
    }
    public Integer getLabel() {
        return this.label;
    }
    
    public void setLabel(Integer label) {
        this.label = label;
    }
    public String getCoordsys() {
        return this.coordsys;
    }
    
    public void setCoordsys(String coordsys) {
        this.coordsys = coordsys;
    }
    public Double getDecj2000() {
        return this.decj2000;
    }
    
    public void setDecj2000(Double decj2000) {
        this.decj2000 = decj2000;
    }
    public Float getDecpmj2000() {
        return this.decpmj2000;
    }
    
    public void setDecpmj2000(Float decpmj2000) {
        this.decpmj2000 = decpmj2000;
    }
    public Integer getDoy() {
        return this.doy;
    }
    
    public void setDoy(Integer doy) {
        this.doy = doy;
    }
    public Float getEpoch() {
        return this.epoch;
    }
    
    public void setEpoch(Float epoch) {
        this.epoch = epoch;
    }
    public String getEquinox() {
        return this.equinox;
    }
    
    public void setEquinox(String equinox) {
        this.equinox = equinox;
    }
    public String getLat() {
        return this.lat;
    }
    
    public void setLat(String lat) {
        this.lat = lat;
    }
    public String getLatpm() {
        return this.latpm;
    }
    
    public void setLatpm(String latpm) {
        this.latpm = latpm;
    }
    public String getLon() {
        return this.lon;
    }
    
    public void setLon(String lon) {
        this.lon = lon;
    }
    public String getLonpm() {
        return this.lonpm;
    }
    
    public void setLonpm(String lonpm) {
        this.lonpm = lonpm;
    }
    public Double getRaj2000() {
        return this.raj2000;
    }
    
    public void setRaj2000(Double raj2000) {
        this.raj2000 = raj2000;
    }
    public Float getRapmj2000() {
        return this.rapmj2000;
    }
    
    public void setRapmj2000(Float rapmj2000) {
        this.rapmj2000 = rapmj2000;
    }
    public String getTgtposlist() {
        return this.tgtposlist;
    }
    
    public void setTgtposlist(String tgtposlist) {
        this.tgtposlist = tgtposlist;
    }
    public short getArraycoord() {
        return this.arraycoord;
    }
    
    public void setArraycoord(short arraycoord) {
        this.arraycoord = arraycoord;
    }
    public short getOnlyoffsets() {
        return this.onlyoffsets;
    }
    
    public void setOnlyoffsets(short onlyoffsets) {
        this.onlyoffsets = onlyoffsets;
    }
    public String getOffsets() {
        return this.offsets;
    }
    
    public void setOffsets(String offsets) {
        this.offsets = offsets;
    }
    public Integer getNaifid() {
        return this.naifid;
    }
    
    public void setNaifid(Integer naifid) {
        this.naifid = naifid;
    }
    public String getNaifname() {
        return this.naifname;
    }
    
    public void setNaifname(String naifname) {
        this.naifname = naifname;
    }




}


