package edu.caltech.ipac.heritage.data.entity.model;
// Generated Oct 14, 2008 7:38:00 PM by Hibernate Tools 3.2.1.GA



/**
 * W3Info generated by hbm2java
 */
public class W3Info  implements java.io.Serializable {


     private String cra;
     private String cdec;
     private double crval1;
     private double crval2;
     private String ctype1;
     private String ctype2;
     private double crpix1;
     private double crpix2;
     private short naxis1;
     private short naxis2;
     private double cdelt1;
     private double cdelt2;
     private double crota2;
     private double epoch;
     private float equinox;
     private double ra1;
     private double dec1;
     private double ra2;
     private double dec2;
     private double ra3;
     private double dec3;
     private double ra4;
     private double dec4;
     private short hdu;
     private double x;
     private double y;
     private double z;

    public W3Info() {
    }

    public W3Info(String cra, String cdec, double crval1, double crval2, String ctype1, String ctype2, double crpix1, double crpix2, short naxis1, short naxis2, double cdelt1, double cdelt2, double crota2, double epoch, float equinox, double ra1, double dec1, double ra2, double dec2, double ra3, double dec3, double ra4, double dec4, short hdu, double x, double y, double z) {
       this.cra = cra;
       this.cdec = cdec;
       this.crval1 = crval1;
       this.crval2 = crval2;
       this.ctype1 = ctype1;
       this.ctype2 = ctype2;
       this.crpix1 = crpix1;
       this.crpix2 = crpix2;
       this.naxis1 = naxis1;
       this.naxis2 = naxis2;
       this.cdelt1 = cdelt1;
       this.cdelt2 = cdelt2;
       this.crota2 = crota2;
       this.epoch = epoch;
       this.equinox = equinox;
       this.ra1 = ra1;
       this.dec1 = dec1;
       this.ra2 = ra2;
       this.dec2 = dec2;
       this.ra3 = ra3;
       this.dec3 = dec3;
       this.ra4 = ra4;
       this.dec4 = dec4;
       this.hdu = hdu;
       this.x = x;
       this.y = y;
       this.z = z;
    }
   
    public String getCra() {
        return this.cra;
    }
    
    public void setCra(String cra) {
        this.cra = cra;
    }
    public String getCdec() {
        return this.cdec;
    }
    
    public void setCdec(String cdec) {
        this.cdec = cdec;
    }
    public double getCrval1() {
        return this.crval1;
    }
    
    public void setCrval1(double crval1) {
        this.crval1 = crval1;
    }
    public double getCrval2() {
        return this.crval2;
    }
    
    public void setCrval2(double crval2) {
        this.crval2 = crval2;
    }
    public String getCtype1() {
        return this.ctype1;
    }
    
    public void setCtype1(String ctype1) {
        this.ctype1 = ctype1;
    }
    public String getCtype2() {
        return this.ctype2;
    }
    
    public void setCtype2(String ctype2) {
        this.ctype2 = ctype2;
    }
    public double getCrpix1() {
        return this.crpix1;
    }
    
    public void setCrpix1(double crpix1) {
        this.crpix1 = crpix1;
    }
    public double getCrpix2() {
        return this.crpix2;
    }
    
    public void setCrpix2(double crpix2) {
        this.crpix2 = crpix2;
    }
    public short getNaxis1() {
        return this.naxis1;
    }
    
    public void setNaxis1(short naxis1) {
        this.naxis1 = naxis1;
    }
    public short getNaxis2() {
        return this.naxis2;
    }
    
    public void setNaxis2(short naxis2) {
        this.naxis2 = naxis2;
    }
    public double getCdelt1() {
        return this.cdelt1;
    }
    
    public void setCdelt1(double cdelt1) {
        this.cdelt1 = cdelt1;
    }
    public double getCdelt2() {
        return this.cdelt2;
    }
    
    public void setCdelt2(double cdelt2) {
        this.cdelt2 = cdelt2;
    }
    public double getCrota2() {
        return this.crota2;
    }
    
    public void setCrota2(double crota2) {
        this.crota2 = crota2;
    }
    public double getEpoch() {
        return this.epoch;
    }
    
    public void setEpoch(double epoch) {
        this.epoch = epoch;
    }
    public float getEquinox() {
        return this.equinox;
    }
    
    public void setEquinox(float equinox) {
        this.equinox = equinox;
    }
    public double getRa1() {
        return this.ra1;
    }
    
    public void setRa1(double ra1) {
        this.ra1 = ra1;
    }
    public double getDec1() {
        return this.dec1;
    }
    
    public void setDec1(double dec1) {
        this.dec1 = dec1;
    }
    public double getRa2() {
        return this.ra2;
    }
    
    public void setRa2(double ra2) {
        this.ra2 = ra2;
    }
    public double getDec2() {
        return this.dec2;
    }
    
    public void setDec2(double dec2) {
        this.dec2 = dec2;
    }
    public double getRa3() {
        return this.ra3;
    }
    
    public void setRa3(double ra3) {
        this.ra3 = ra3;
    }
    public double getDec3() {
        return this.dec3;
    }
    
    public void setDec3(double dec3) {
        this.dec3 = dec3;
    }
    public double getRa4() {
        return this.ra4;
    }
    
    public void setRa4(double ra4) {
        this.ra4 = ra4;
    }
    public double getDec4() {
        return this.dec4;
    }
    
    public void setDec4(double dec4) {
        this.dec4 = dec4;
    }
    public short getHdu() {
        return this.hdu;
    }
    
    public void setHdu(short hdu) {
        this.hdu = hdu;
    }
    public double getX() {
        return this.x;
    }
    
    public void setX(double x) {
        this.x = x;
    }
    public double getY() {
        return this.y;
    }
    
    public void setY(double y) {
        this.y = y;
    }
    public double getZ() {
        return this.z;
    }
    
    public void setZ(double z) {
        this.z = z;
    }




}


