/*
 * License information at https://github.com/Caltech-IPAC/firefly/blob/master/License.txt
 */
//=== File Prolog =============================================================
//	This code was developed by NASA, Goddard Space Flight Center, Code 588
//	for the Scientist's Expert Assistant (SEA) project.
//
//--- Contents ----------------------------------------------------------------
//	class AstroDatabaseException
//
//--- Description -------------------------------------------------------------
//	Any exception that is generated by an AstroDatabaseClient that is
//	directly related to the database and isn't covered by the java.io or
//	java.net exceptions should subclass from this exception.
//
//--- Notes -------------------------------------------------------------------
//
//--- Development History -----------------------------------------------------
//
//	04/29/98	J. Jones / 588
//
//		Original implementation.
//
//--- Warning -----------------------------------------------------------------
//	This software is property of the National Aeronautics and Space
//	Administration.  Unauthorized use or duplication of this software is
//	strictly prohibited.  Authorized users are subject to the following
//	restrictions:
//	*	Neither the author, their corporation, nor NASA is responsible for
//		any consequence of the use of this software.
//	*	The origin of this software must not be misrepresented either by
//		explicit claim or by omission.
//	*	Altered versions of this software must be plainly marked as such.
//	*	This notice may not be removed or altered.
//
//=== End File Prolog =========================================================

package edu.caltech.ipac.astro.ned;

/**
 * Any exception that is generated by an AstroDatabaseClient that is
 * directly related to the database and isn't covered by the java.io or
 * java.net exceptions should subclass from this exception.
 *
 * <P>This code was developed by NASA, Goddard Space Flight Center, Code 588
 * for the Scientist's Expert Assistant (SEA) project.
 *
 * @version		04/29/98
 * @author		J. Jones / 588
**/
public class AstroDatabaseException extends Exception
{
	public AstroDatabaseException()
	{
		super();
	}

	public AstroDatabaseException(String message)
	{
		super(message);
	}
}


